### ISSUE TITLE
Connection first hangs and then close

### ISSUE THREAD

**Issue by carousel** [vim-vdebug/vdebug#115]
I've trying to fix the problem that I have with the help of other people's issuse but got no lack. So I opened new one. 
Simply connection hangs and after some time ( 20 sec ) it is closed. I tried to change host and port name (on multiple locations) but still nothing changes. I am using Ubuntu and Vim 7.4.
Any help is welcome. Thank you.

**Comment by reesew** [comment]
vdebug was broken for me (hanging on both sides), but cleaning up the old swap files fixed it for me as well
