### ISSUE TITLE
persistent breakpoints

### ISSUE THREAD

**Issue by mikedfunk** [vim-vdebug/vdebug#129]
If I close Vim and reopen, my breakpoints have disappeared. Are they supposed to persist across sessions? I can't find anything about it in the docs.

**Comment by ahakanbaba** [comment]
I see that in this issue there is a relevant mention of disabling/enabling of breakpoints. I think supporting that would improve the usability of the plugin significantly. Since this issue has a different topic I have created #393 for that.
