### ISSUE TITLE
Breakpoint in script that is launched after some process

### ISSUE THREAD

**Issue by novito** [vim-vdebug/vdebug#141]
I have a question and I am not sure if this is related to Vdebug or Xdebug itself. My coworker uses PHPStorm and he has it work it fine.

Basically we have a script that is called after filling some forms. So, we have a breakpoint in that script.

When I launch Vdebug by pressing F5, I see that it stops at my index.php. Then, if I press F5 so that I can go to my forms, the Vdebug goes from 'running' to 'stopped' and once I reach that script that process the forms it doesn't stop in the breakpoint (obviously because the debugger is not running). So, my question is, how can I make vdebug to be running until I say so (my coworker here has a button to stop the debugger).

**Comment by byronkingz** [comment]
I have the same problem,has it  been solved?

**Comment by joonty** [comment]
Hi @byronkingz this issue is probably down to a set-up issue, not a bug (could be wrong though). Could you create a log file (see my comment above) and paste it here? That will help with context.

Thanks

**Comment by byronkingz** [comment]
These are my configuration:

    let g:vdebug_options_defaults = {
    \    "port" : 9000,
    \    "timeout" : 120,
    \    "server" : '',
    \    "on_close" : 'detach',
    \    "break_on_open" : 0,
    \    "ide_key" : '',
    \    "debug_window_level" : 0,
    \    "debug_file_level" : 2,
    \    "debug_file" : "~/vdebug.log",
    \    "path_maps" : {},
    \    "watch_window_style" : 'expanded',
    \    "marker_default" : '⬦',
    \    "marker_closed_tree" : '▸',
    \    "marker_open_tree" : '▾',
    \    "continuous_mode"  : 0
    \}

**Comment by byronkingz** [comment]
and these are my log files:

![image](https://cloud.githubusercontent.com/assets/8175107/11809506/53e07e4c-a362-11e5-982e-86b01218cf83.png)
![image](https://cloud.githubusercontent.com/assets/8175107/11809519/67ef1e48-a362-11e5-962c-44bf750e6408.png)
![image](https://cloud.githubusercontent.com/assets/8175107/11809529/7c1aa86a-a362-11e5-9932-f2bd45b96f30.png)

>once the request is done (I add XDEBUG_SESSION_START=1 on my URL), the debugger goes to:

>Status:stopped
>Listening on ...
>Not connected

>Debugging session has ended

Thanks!

**Comment by joonty** [comment]
@byronkingz as you're using cygwin you'll need to add path maps, since the real system path is going to be `F:/etc/etc...`. Try adding:

```vim
let g:vdebug_options['path_maps'] = { 'F:' : '/cygdrive/f' }
```

This will do the substitution in file paths for you.

**Comment by byronkingz** [comment]
@joonty Great! It's useful.Thank you!
