### ISSUE TITLE
Random crash when debugging PHP with xdebug

### ISSUE THREAD

**Issue by kminh** [vim-vdebug/vdebug#147]
Hi, thank you for a nice plugin.

The debugger seems to crash randomly when debugging, I got this error:

```
[ERROR] {Tue 04 2014 20:44:11} An error occured: <type 'exceptions.TypeError'> Traceback (most recent call last):
File "~/.vim/bundle/vdebug/plugin/python/start_vdebug.py", line 31, in run self.runner.run()
File "~/.vim/bundle/vdebug/plugin/python/vdebug/runner.py", line 165, in run self.refresh(res)
File "~/.vim/bundle/vdebug/plugin/python/vdebug/runner.py", line 99, in refresh if str(status) == "interactive":
TypeError: __str__ returned non-string (type NoneType)
```

when debugging a very simple PHP script, for example:

```
<?php
$test = array();
for ($i = 0; $i < 1000; $i++) {
    $test[] = $i; (line break here)
}
```

I keep pressing F2 and then pause for a second and then press F2 again it will show the error message (randomly).

My environments:
- php 5.5.9 with mod_fcgi enabled
- xdebug 2.2.3-3 (using port 9001)
- vim 7.4 1-135

Hope you can look into this, thank you.

**Comment by stephenplatz** [comment]
@kminh I'm having this exact same issue, any other pointers for the fix, which conf file do I adjust, I'm using apache2?
