### ISSUE TITLE
Set size of windows?

### ISSUE THREAD

**Issue by jaredcobb** [vim-vdebug/vdebug#149]
Not really an issue, just a question.  Is there a setting or a way to change the default size of the windows (specifically the DebuggerWatch, DebuggerStack, DebuggerStatus windows)?

I know they're relative to my overall window size, but I find myself always wanting the DebuggerWatch to be maybe 80% height and the other two to be 10% each.  (Or even not having the DebuggerStatus show at all).

Thanks!

**Comment by WouterSioen** [comment]
+1

**Comment by lucc** [comment]
@paprykarz this topic is also addressed in #360. As I understand it configuring the interface is a topic for [2.1](https://github.com/vim-vdebug/vdebug/projects/3). Maybe your commits can be turned into a pull request to help with that?

**Comment by lucc** [comment]
I just fiddled around a bit more and found a way to adjust the window height a bit even with the current code.  I used this vdebug options:
```vim
let g:vdebug_options = {
      \   'window_commands': {
      \     'DebuggerWatch': 'vertical belowright new',
      \     'DebuggerStack': 'belowright new +res5',
      \     'DebuggerStatus': 'belowright new +res5'
      \   },
      \ }
```
The values are copied from the plugin file (the defaults). I just added the `+res5` part. See `:h VdebugOptionList`, `:h :new`, `:h +cmd` and `:h :res`.

**Comment by Garethp** [comment]
@BlackIkeEagle This issue can be closed now
