### ISSUE TITLE
Can not connect to remote session

### ISSUE THREAD

**Issue by 3cooper** [vim-vdebug/vdebug#154]
I have a server running a website that I'd like to debug using vdebug on my local machine.  I have XDebug working correctly using both Codebug and MacGDBp.  So it seems that XDebug is set up correctly on both machines.  When I try to use vdebug - I set a break point and his F5.  I see that it is listening for connections.  I refresh my browser that has XDEBUG_SESSION_START=1 in the query string but the page reloads and vdebug never stops it.

Logs - 
[Info] {Fri 18 2014 13:40:35} No connection was made

.vimrc
let g:vdebug_options = {}
let g:vdebug_options["port"] = 9000
let g:vdebug_options["break_on_open"] = 0

let g:vdebug_options["debug_file"] = "/tmp/vdebug.log"
let g:vdebug_options["debug_file_level"] = 2
let g:vdebug_options["path_maps"] = {
\    "/home/me/remoteCode": "/Users/me/localCode"
}

Vim version info - https://gist.github.com/3cooper/11056275

Can you see anything I might have wrong?

**Comment by baptx** [comment]
@exussum12 is it normal that setting `xdebug.remote_host` to my IP address on the web server does not work? In `.vimrc` I correctly replaced 127.0.0.1 by the web server IP address. At least the SSH tunnel solution is working.

**Comment by exussum12** [comment]
@baptx that setting means conneting back, you host the port yourself, the remote host means connect back to you.

If that doesnt work then something is blocking the traffic between you (NAT on your router maybe?)

**Comment by baptx** [comment]
@exussum12 I don't think it is blocked because it also fails through my VPN on port TCP 443 and with ports 9000 open (I added the IP of the VPN in `xdebug.remote_host` when testing with the VPN). I also tried with `xdebug.remote_connect_back = 1` instead of `xdebug.remote_host` like explained in Xdebug documentation. And @3cooper said it worked for other Xdebug clients, so you can confirm that remote debugging with vdebug without SSH tunnel is working for you?

**Comment by exussum12** [comment]
@baptx there are a few things, The server option if you set as 0.0.0.0 that means listen on all interfaces.

The xdebug server as you said is hosted on your machine, so a public route to that IP is needed (port forward with NAT, or open firewall port)

SSH tunneling moves the remote port connection to be a local one, which is a better option (IMO) though does require an active SSH connection
