### ISSUE TITLE
Restore previous (overwritten) mappings after stopping the debugger

### ISSUE THREAD

**Issue by blueyed** [vim-vdebug/vdebug#16]
After stopping the debugger any previously defined mappings that have been overwritten by vdebug should get restored.

See https://github.com/joonty/vdebug/commit/38d0506ab897f6433c1f1b704c54e7035e0c30a5 , where the initial dynamic mapping had been introduced.

`map()` should query the current mapping and `unmap` should restore them.

**Comment by kevinc1984** [comment]
Hi There,

I'm glad you guys have this feature implemented, but I can't seem to get it working. In my vimrc file I have:
```
nmap <F2> :NERDTreeToggle<CR>
```
Before vdebug is running, it works. After closing vdebug, it does not. Does my mapping need anything special?

Nowhere in my vdebug log file does it trigger the "Storing existing key mapping" phrase, nor does it trigger any unmapping phrases on close so it is either not being recognized in the vimrc file or the tempfile created with `mkexrc!` is not working.

Here is the submodule git record for vdebug:
```
13640276b95125f84f3f1518f07afb3c2542ac35 vim/bundle/vdebug (v1.4.1-77-g1364027)
```

Any thoughts?
