### ISSUE TITLE
Does not work with VIM + python3

### ISSUE THREAD

**Issue by bboldi** [vim-vdebug/vdebug#174]
I have tried to get this working with no luck with python3 ... here is my $vim --version | grep python

+cscope          +lispindent      +python3         +vreplace

-L/usr/lib/python3.4/config-3.4m -lpython3.4m

**Comment by l0rb** [comment]
Still planning on updating it for python3 ?

**Comment by BlackIkeEagle** [comment]
@l0rb yes still planning for python3, its a bit delayed
