### ISSUE TITLE
VdebugOpt defines "path_maps" as string

### ISSUE THREAD

**Issue by askobara** [vim-vdebug/vdebug#228]
Hello!

Currently if I try run debug session after using
`:VdebugOpt path_maps {'/remote/path':'/local/path'}`
I get error

```
...
File "/home/user/.vim/bundle/vdebug/plugin/python/vdebug/opts.py", line 30, in get 
return as_type(inst.options[name]) 
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

Because `g:vdebug_options["path_maps"]` is a string instead dictionary as expect

**Comment by BlackIkeEagle** [comment]
Could you elaborate further. The path mapping works if set in the config but not when using the VdebugOpt path_maps .

I'm using `let g:vdebug_options["path_maps"] = {}` and that works fine.

**Comment by askobara** [comment]
Yep, you are totally right! If using `let g:vdebug_options["path_maps"]` all works as expected. But while reading docs I found `VdebugOpt` first and unsuccessfully tried to use it in command mode.

**Comment by BlackIkeEagle** [comment]
@askobara k thx so its a specific bug to VdebugOpt :)

**Comment by joonty** [comment]
Thanks for raising this. I remember seeing this now, but kept quiet about it, and planned to fix it. Obviously that plan fell by the wayside... :grin:

**Comment by askobara** [comment]
Oh, no problem! It's no critical bug :)

**Comment by mikedfunk** [comment]
+1 I have to change my vimrc and reopen vim if I'm running via cli on the host machine :(
