### ISSUE TITLE
breakpoints  in a django-based project does not take effect

### ISSUE THREAD

**Issue by littlecarpenter** [vim-vdebug/vdebug#253]
It is a little like the issue mentioned by x-yuri[Unable to run to breakpoint](https://github.com/joonty/vdebug/issues/245)
The breakpoints in initial file works fine, but breakpoints in Entry function of a url in urls.py will not stop.

**Comment by cincodenada** [comment]
Are you debugging locally, or on a remote system?

Could you [turn on logging](https://github.com/joonty/vdebug#debugging), attempt to set the breakpoint and run the program, and paste the log here?

**Comment by littlecarpenter** [comment]
`- [Info] { 16 2016 14:33:14} Stepping over
 - [Debug] { 16 2016 14:33:14} Command: step_over -i 86
 - [Debug] { 16 2016 14:33:14} Response: <?xml version="1.0" encoding="utf-8"?>
 <response xmlns="urn:debugger_protocol_v1" command="step_over" status="break" reason="ok" transaction_id="86"/>
 - [Info] { 16 2016 14:33:14} Getting stack information
 - [Debug] { 16 2016 14:33:14} Command: stack_get -i 87
 - [Debug] { 16 2016 14:33:14} Response: <?xml version="1.0" encoding="utf-8"?>
 <response xmlns="urn:debugger_protocol_v1" command="stack_get" depth="4" transaction_id="87"><stack level="0" type="file" filename="file:///usr/local/lib/python2.7/dist-packages/django/core$management/__init__.py" lineno="196" where="fetch_command"/><stack level="1" type="file" filename="file:///usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py" lineno="3$5" where="execute"/><stack level="2" type="file" filename="file:///usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py" lineno="353" where="execute_from_command_line"/><$tack level="3" type="file" filename="file:///home/jerry/code/workspace/cloud/main.py" lineno="27" where="&lt;module&gt;"/></response>
 - [Info] { 16 2016 14:33:14} Moving to current position in source window
 - [Info] { 16 2016 14:33:14} Placing pointer sign on line 196
 - [Info] { 16 2016 14:33:14} Getting Locals variables
 - [Debug] { 16 2016 14:33:14} Command: context_get -i 88 -c 0
 - [Debug] { 16 2016 14:33:14} Response: <?xml version="1.0" encoding="utf-8"?>
 <response xmlns="urn:debugger_protocol_v1" command="context_get" context="0" transaction_id="88"><property  type="str" children="0" size="26"><value encoding="base64"><![CDATA[ZGphbmdvLmNvb$RyaWIuc3RhdGljZmlsZXM=
 ]]></value><name encoding="base64"><![CDATA[YXBwX25hbWU=
 ]]></name><fullname encoding="base64"><![CDATA[YXBwX25hbWU=
 ]]></fullname></property><property  pagesize="10" numchildren="29" children="1" type="dict" page="0" size="29"><name encoding="base64"><![CDATA[Y29tbWFuZHM=
 ]]></name><fullname encoding="base64"><![CDATA[Y29tbWFuZHM=
 ]]></fullname></property><property  pagesize="10" numchildren="12" children="1" type="Command" page="0" size="0"><name encoding="base64"><![CDATA[a2xhc3M=
 ]]></name><fullname encoding="base64"><![CDATA[a2xhc3M=
 ]]></fullname></property><property  pagesize="10" numchildren="3" children="1" type="ManagementUtility" page="0" size="0"><name encoding="base64"><![CDATA[c2VsZg==
 ]]></name><fullname encoding="base64"><![CDATA[c2VsZg==
 ]]></fullname></property><property  type="str" children="0" size="9"><value encoding="base64"><![CDATA[cnVuc2VydmVy
 ]]></value><name encoding="base64"><![CDATA[c3ViY29tbWFuZA==
 ]]></name><fullname encoding="base64"><![CDATA[c3ViY29tbWFuZA==
 ]]></fullname></property></response>
 - [Info] { 16 2016 14:33:14} Writing 5 properties to the context window
 - [Debug] { 16 2016 14:33:14} Writing to context window:
 [ *Locals ] [ Globals ] [ Code Objects ]

 - Locals at /usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py:196

  80 app_name = (str [26]) `django.contrib.staticfiles`
   |
    76 commands = (dict [29])
     |
      76 klass = (Command [12])
     |
      76 self = (ManagementUtility [3])
     |
      80 subcommand = (str [9]) `runserver`

      - [Info] { 16 2016 14:33:16} Stepping over
      - [Debug] { 16 2016 14:33:16} Command: step_over -i 89
`

**Comment by littlecarpenter** [comment]
The log of Similar case is listed below.

After the last log, vim hangs until the "python -S ~/myBin/Komodo-PythonRemoteDebugging-8.5.4-86985-linux-x86_64/pydbgp  -d localhost:9000 main.py" is killed.

BTW, django was run in 127.0.0.1:8000.
=================================================================
- [Debug] {三 17 2016 15:52:09} Command: stack_get -i 179
- [Debug] {三 17 2016 15:52:09} Response: <?xml version="1.0" encoding="utf-8"?>
<response xmlns="urn:debugger_protocol_v1" command="stack_get" depth="4" transaction_id="179"><stack level="0" type="file" filename="file:///usr/local/lib/python2.7/dist-packages/django/core/management/base.py" lineno="347" where="run_from_argv"/><stack level="1" type="file" filename="file:///usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py" lineno="345" where="execute"/><stack level="2" type="file" filename="file:///usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py" lineno="353" where="execute_from_command_line"/><stack level="3" type="file" filename="file:///home/jerry/code/workspace/cloud/main.py" lineno="27" where="&lt;module&gt;"/></response>
- [Info] {三 17 2016 15:52:09} Moving to current position in source window
- [Debug] {三 17 2016 15:52:09} Setting source line number: 347
- [Info] {三 17 2016 15:52:10} Placing pointer sign on line 347
- [Debug] {三 17 2016 15:52:10} ** GetContextEvent
- [Info] {三 17 2016 15:52:10} Getting Locals variables
- [Debug] {三 17 2016 15:52:10} Command: context_get -i 180 -c 0
- [Debug] {三 17 2016 15:52:10} Response: <?xml version="1.0" encoding="utf-8"?>
<response xmlns="urn:debugger_protocol_v1" command="context_get" context="0" transaction_id="180"><property  type="tuple" children="0" size="2"><value><![CDATA[()]]></value><name><![CDATA[args]]></name><fullname><![CDATA[args]]></fullname></property><property  pagesize="10" numchildren="3" children="1" type="list" page="0" size="78"><value encoding="base64"><![CDATA[WycvaG9tZS90ZXJyeS9jb2RlL3dvcmtzcGFjZS9sdV9jbG91ZC9tYWluLnB5JywgJ3J1bnNlcnZl
cicsICcxMjcuMC4wLjE6ODAwMCdd
]]></value><name><![CDATA[argv]]></name><fullname><![CDATA[argv]]></fullname></property><property  pagesize="10" numchildren="11" children="1" type="dict" page="0" size="242"><value encoding="base64"><![CDATA[eyd1c2Vfc3RhdGljX2hhbmRsZXInOiBUcnVlLCAnc2V0dGluZ3MnOiBOb25lLCAncHl0aG9ucGF0
aCc6IE5vbmUsICd2ZXJib3NpdHknOiAxLCAndHJhY2ViYWNrJzogRmFsc2UsICdhZGRycG9ydCc6
ICcxMjcuMC4wLjE6ODAwMCcsICdub19jb2xvcic6IEZhbHNlLCAndXNlX2lwdjYnOiBGYWxzZSwg
J3VzZV90aHJlYWRpbmcnOiBUcnVlLCAndXNlX3JlbG9hZGVyJzogVHJ1ZSwgJ2luc2VjdXJlX3Nl
cnZpbmcnOiBGYWxzZX0=
]]></value><name><![CDATA[cmd_options]]></name><fullname><![CDATA[cmd_options]]></fullname></property><property  pagesize="10" numchildren="11" children="1" type="Namespace" page="0" size="218"><value encoding="base64"><![CDATA[TmFtZXNwYWNlKGFkZHJwb3J0PScxMjcuMC4wLjE6ODAwMCcsIGluc2VjdXJlX3NlcnZpbmc9RmFs
c2UsIG5vX2NvbG9yPUZhbHNlLCBweXRob25wYXRoPU5vbmUsIHNldHRpbmdzPU5vbmUsIHRyYWNl
YmFjaz1GYWxzZSwgdXNlX2lwdjY9RmFsc2UsIHVzZV9yZWxvYWRlcj1UcnVlLCB1c2Vfc3RhdGlj
X2hhbmRsZXI9VHJ1ZSwgdXNlX3RocmVhZGluZz1UcnVlLCB2ZXJib3NpdHk9MSk=
]]></value><name><![CDATA[options]]></name><fullname><![CDATA[options]]></fullname></property><property  pagesize="10" numchildren="11" children="1" type="CommandParser" page="0" size="250"><value encoding="base64"><![CDATA[Q29tbWFuZFBhcnNlcihwcm9nPXUnbWFpbi5weSBydW5zZXJ2ZXInLCB1c2FnZT1Ob25lLCBkZXNj
cmlwdGlvbj0nU3RhcnRzIGEgbGlnaHR3ZWlnaHQgV2ViIHNlcnZlciBmb3IgZGV2ZWxvcG1lbnQg
YW5kIGFsc28gc2VydmVzIHN0YXRpYyBmaWxlcy4nLCB2ZXJzaW9uPU5vbmUsIGZvcm1hdHRlcl9j
bGFzcz08Y2xhc3MgJ2FyZ3BhcnNlLkhlbHBGb3JtYXR0ZXInPiwgY29uZmxpY3RfaGFuZGxlcj0n
ZXJyb3InLCBhZGRfaGVscD1UcnVlKQ==
]]></value><name encoding="base64"><![CDATA[cGFyc2Vy
]]></name><fullname encoding="base64"><![CDATA[cGFyc2Vy
]]></fullname></property><property  pagesize="10" numchildren="12" children="1" type="Command" page="0" size="0"><name encoding="base64"><![CDATA[c2VsZg==
]]></name><fullname encoding="base64"><![CDATA[c2VsZg==
]]></fullname></property></response>
- [Info] {三 17 2016 15:52:10} Writing 6 properties to the window
- [Debug] {三 17 2016 15:52:10} Writing to window:
[ *Locals ] [ Globals ] [ Code Objects ]

- Locals at /usr/local/lib/python2.7/dist-packages/django/core/management/base.py:347

 ⬦ args = (tuple [2]) ()
 |
 ▸ argv = (list [3])
 |
 ▸ cmd_options = (dict [11])
 |
 ▸ options = (Namespace [11])
 |
 ▸ parser = (CommandParser [11])
 |
 ▸ self = (Command [12])

- [Debug] {三 17 2016 15:52:10} ** TraceRefreshEvent
- [Debug] {三 17 2016 15:52:10} ** StepOverEvent
- [Info] {三 17 2016 15:52:10} Stepping over
- [Debug] {三 17 2016 15:52:10} Command: step_over -i 181
- [Debug] {三 17 2016 15:52:10} Response: <?xml version="1.0" encoding="utf-8"?>
<response xmlns="urn:debugger_protocol_v1" command="step_over" status="break" reason="ok" transaction_id="181"/>
- [Debug] {三 17 2016 15:52:10} ** RefreshEvent
- [Info] {三 17 2016 15:52:10} Getting stack information
- [Debug] {三 17 2016 15:52:10} Command: stack_get -i 182
- [Debug] {三 17 2016 15:52:10} Response: <?xml version="1.0" encoding="utf-8"?>
<response xmlns="urn:debugger_protocol_v1" command="stack_get" depth="4" transaction_id="182"><stack level="0" type="file" filename="file:///usr/local/lib/python2.7/dist-packages/django/core/management/base.py" lineno="348" where="run_from_argv"/><stack level="1" type="file" filename="file:///usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py" lineno="345" where="execute"/><stack level="2" type="file" filename="file:///usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py" lineno="353" where="execute_from_command_line"/><stack level="3" type="file" filename="file:///home/jerry/code/workspace/cloud/main.py" lineno="27" where="&lt;module&gt;"/></response>
- [Info] {三 17 2016 15:52:10} Moving to current position in source window
- [Debug] {三 17 2016 15:52:10} Setting source line number: 348
- [Info] {三 17 2016 15:52:10} Placing pointer sign on line 348
- [Debug] {三 17 2016 15:52:10} ** GetContextEvent
- [Info] {三 17 2016 15:52:10} Getting Locals variables
- [Debug] {三 17 2016 15:52:10} Command: context_get -i 183 -c 0
- [Debug] {三 17 2016 15:52:10} Response: <?xml version="1.0" encoding="utf-8"?>
<response xmlns="urn:debugger_protocol_v1" command="context_get" context="0" transaction_id="183"><property  type="tuple" children="0" size="2"><value><![CDATA[()]]></value><name><![CDATA[args]]></name><fullname><![CDATA[args]]></fullname></property><property  pagesize="10" numchildren="3" children="1" type="list" page="0" size="78"><value encoding="base64"><![CDATA[WycvaG9tZS90ZXJyeS9jb2RlL3dvcmtzcGFjZS9sdV9jbG91ZC9tYWluLnB5JywgJ3J1bnNlcnZl
cicsICcxMjcuMC4wLjE6ODAwMCdd
]]></value><name><![CDATA[argv]]></name><fullname><![CDATA[argv]]></fullname></property><property  pagesize="10" numchildren="11" children="1" type="dict" page="0" size="242"><value encoding="base64"><![CDATA[eyd1c2Vfc3RhdGljX2hhbmRsZXInOiBUcnVlLCAnc2V0dGluZ3MnOiBOb25lLCAncHl0aG9ucGF0
aCc6IE5vbmUsICd2ZXJib3NpdHknOiAxLCAndHJhY2ViYWNrJzogRmFsc2UsICdhZGRycG9ydCc6
ICcxMjcuMC4wLjE6ODAwMCcsICdub19jb2xvcic6IEZhbHNlLCAndXNlX2lwdjYnOiBGYWxzZSwg
J3VzZV90aHJlYWRpbmcnOiBUcnVlLCAndXNlX3JlbG9hZGVyJzogVHJ1ZSwgJ2luc2VjdXJlX3Nl
cnZpbmcnOiBGYWxzZX0=
]]></value><name><![CDATA[cmd_options]]></name><fullname><![CDATA[cmd_options]]></fullname></property><property  pagesize="10" numchildren="11" children="1" type="Namespace" page="0" size="218"><value encoding="base64"><![CDATA[TmFtZXNwYWNlKGFkZHJwb3J0PScxMjcuMC4wLjE6ODAwMCcsIGluc2VjdXJlX3NlcnZpbmc9RmFs
c2UsIG5vX2NvbG9yPUZhbHNlLCBweXRob25wYXRoPU5vbmUsIHNldHRpbmdzPU5vbmUsIHRyYWNl
YmFjaz1GYWxzZSwgdXNlX2lwdjY9RmFsc2UsIHVzZV9yZWxvYWRlcj1UcnVlLCB1c2Vfc3RhdGlj
X2hhbmRsZXI9VHJ1ZSwgdXNlX3RocmVhZGluZz1UcnVlLCB2ZXJib3NpdHk9MSk=
]]></value><name><![CDATA[options]]></name><fullname><![CDATA[options]]></fullname></property><property  pagesize="10" numchildren="11" children="1" type="CommandParser" page="0" size="250"><value encoding="base64"><![CDATA[Q29tbWFuZFBhcnNlcihwcm9nPXUnbWFpbi5weSBydW5zZXJ2ZXInLCB1c2FnZT1Ob25lLCBkZXNj
cmlwdGlvbj0nU3RhcnRzIGEgbGlnaHR3ZWlnaHQgV2ViIHNlcnZlciBmb3IgZGV2ZWxvcG1lbnQg
YW5kIGFsc28gc2VydmVzIHN0YXRpYyBmaWxlcy4nLCB2ZXJzaW9uPU5vbmUsIGZvcm1hdHRlcl9j
bGFzcz08Y2xhc3MgJ2FyZ3BhcnNlLkhlbHBGb3JtYXR0ZXInPiwgY29uZmxpY3RfaGFuZGxlcj0n
ZXJyb3InLCBhZGRfaGVscD1UcnVlKQ==
]]></value><name encoding="base64"><![CDATA[cGFyc2Vy
]]></name><fullname encoding="base64"><![CDATA[cGFyc2Vy
]]></fullname></property><property  pagesize="10" numchildren="12" children="1" type="Command" page="0" size="0"><name encoding="base64"><![CDATA[c2VsZg==
]]></name><fullname encoding="base64"><![CDATA[c2VsZg==
]]></fullname></property></response>
- [Info] {三 17 2016 15:52:10} Writing 6 properties to the window
- [Debug] {三 17 2016 15:52:10} Writing to window:
[ *Locals ] [ Globals ] [ Code Objects ]

- Locals at /usr/local/lib/python2.7/dist-packages/django/core/management/base.py:348

 ⬦ args = (tuple [2]) ()
 |
 ▸ argv = (list [3])
 |
 ▸ cmd_options = (dict [11])
 |
 ▸ options = (Namespace [11])
 |
 ▸ parser = (CommandParser [11])
 |
 ▸ self = (Command [12])

- [Debug] {三 17 2016 15:52:10} ** TraceRefreshEvent
- [Debug] {三 17 2016 15:52:11} ** StepOverEvent
- [Info] {三 17 2016 15:52:11} Stepping over
- [Debug] {三 17 2016 15:52:11} Command: step_over -i 184

**Comment by BlackIkeEagle** [comment]
might need retesting with v2, if still present please open a new issue
