### ISSUE TITLE
Missing DebuggerInterface

### ISSUE THREAD

**Issue by ghost** [vim-vdebug/vdebug#26]
Hi there,

I suspect this might be a python issue, but since there are no more specific requirements listed than that...

I get this error starting vim - any pointers welcome:

> Error detected while processing /var/home/martinr/.vim/bundle/vdebug/plugin/vdebug.vim:
> line   38:
> Traceback (most recent call last):
>  File "<string>", line 1, in ?
>  File "/var/home/martinr/.vim/bundle/vdebug/plugin/python/start_vdebug.py", line 10, in ?
>    import vdebug.runner
>  File "/var/home/martinr/.vim/bundle/vdebug/plugin/python/vdebug/runner.py", line 3, in ?
>    import vdebug.dbgp
>  File "/var/home/martinr/.vim/bundle/vdebug/plugin/python/vdebug/dbgp.py", line 576
>    self.has_children = True if children > 0 else False
>                               ^
> SyntaxError: invalid syntax
> line   83:
> Traceback (most recent call last):
>  File "<string>", line 1, in ?
> NameError: name 'DebuggerInterface' is not defined
> Press ENTER or type command to continue

**Comment by stephenplatz** [comment]
I'm getting a similar error with python 2.7

`Error detected while processing function provider#python#Call:
line   18:
Traceback (most recent call last):
  File "/home/steve/.janus/vdebug/plugin/python/start_vdebug.py", line 10, in <module>
    import vdebug.runner
ImportError: No module named runner
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'DebuggerInterface' is not defined
`
This wasn't happening prior to yesterday when I switch to the v2-integration branch to try it, then switched back to the master branch.
