### ISSUE TITLE
Cannot remove old breakpoint from an empty line.

### ISSUE THREAD

**Issue by Roy-Orbison** [vim-vdebug/vdebug#292]
Get this error message: `Cannot set a breakpoint on an empty line`
Toggling should always allow removal based on line's sign, only chucking an error if one's trying to *add to* an empty line.

Also consider emulating browser debuggers which add a marker to the next available non-empty line. If you're feeling really fancy, "animate" another sign type (so as not to affect actual breakpoint signs) with the same sign style, down to that line by progressively toggling it on and off preceding lines.

**Comment by webastien** [comment]
not solving the problem but if you need to remove an old breakpoint which cannot be done by the command or shortcut, you can type `BreakpointRemove ID` (use `BreakpointWindow` to get the ID).

**Comment by Roy-Orbison** [comment]
Found that. Also useful for when a breakpoint does not want to be removed
even though it's on a code line.

**Comment by mortona42** [comment]
+1 for this issue. I'd like to see invalid breakpoints removed automatically, if possible.

Roy, are you saying if you put a breakpoint on an invalid line (like a multi-line array definition), it should automatically be placed on the right line? If so, that sounds awesome. There have been many times I thought I set a valid breakpoint, only to realize it didn't work as expected.

**Comment by Roy-Orbison** [comment]
@mortona42 That, too. It should only add to the next breakable line.

**Comment by Taluu** [comment]
> Found that. Also useful for when a breakpoint does not want to be removed
even though it's on a code line.

It's when you add another line of code before the breakpoint line. Adding a line before said breakpoint should imo either shift the breakpoint (best UX solution imo) or delete it automatically...

**Comment by Roy-Orbison** [comment]
Thanks @Taluu, I now see what line breakpoints are actually on, from the `:BreakkpointWindow`, and toggling it on the listed line removes the erroneous mark.
