### ISSUE TITLE
Vdebug causing SIGSEGV in Vim, and jibberish python errors.

### ISSUE THREAD

**Issue by s-c-p** [vim-vdebug/vdebug#334]
To reproduce this error:

 0. Start live Ubuntu-GNOME 16.04
 1. Get vim 7.4
 2. Setup Vdebug for python 3 (I used pydbgp version 11.0.2 from activestate)
 3. start Vdebug*ing*`test.py` of `github.com/s-c-p/simple-reactive-py`
 4. Just keep stepping over and vim will crash at `main()` 

Seg-faults seem to be serious trouble, perhaps similar to https://github.com/vim-vdebug/vdebug/issues/320

______

**Ubuntu Reports**

vim.basic crashed with SIGSEGV in PyGC_Collect()

and

`vim --version` reports

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
Included patches: 1-1689
Extra patches: 8.0.0056
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +tag_binary
+arabic          +file_in_path    +mouse_sgr       +tag_old_static
+autocmd         +find_in_path    -mouse_sysmouse  -tag_any_white
-balloon_eval    +float           +mouse_urxvt     -tcl
-browse          +folding         +mouse_xterm     +terminfo
++builtin_terms  -footer          +multi_byte      +termresponse
+byte_offset     +fork()          +multi_lang      +textobjects
+channel         +gettext         -mzscheme        +timers
+cindent         -hangul_input    +netbeans_intg   +title
-clientserver    +iconv           +packages        -toolbar
-clipboard       +insert_expand   +path_extra      +user_commands
+cmdline_compl   +job             -perl            +vertsplit
+cmdline_hist    +jumplist        +persistent_undo +virtualedit
+cmdline_info    +keymap          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       -python          +vreplace
+cscope          +lispindent      +python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con      -lua             +rightleft       +writebackup
+diff            +menu            -ruby            -X11
+digraphs        +mksession       +scrollbind      -xfontset
-dnd             +modify_fname    +signs           -xim
-ebcdic          +mouse           +smartindent     -xsmp
+emacs_tags      -mouseshape      +startuptime     -xterm_clipboard
+eval            +mouse_dec       +statusline      -xterm_save
+ex_extra        +mouse_gpm       -sun_workshop    -xpm
+extra_search    -mouse_jsbterm   +syntax          
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -Wdate-time  -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: gcc   -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl     -L/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu -lpython3.5m -lpthread -ldl -lutil -lm      
```

**Comment by s-c-p** [comment]
Why is nobody seeing this?

**Comment by s-c-p** [comment]
The above comment was just to increase number of comments, so on issues pages people will think "Oh! This issue is getting a lot of attention, I should look at it too."

**Comment by learningJava4ds** [comment]
Why is nobody addressing this issue

**Comment by BlackIkeEagle** [comment]
@s-c-p Sorry I missed this

**Comment by BlackIkeEagle** [comment]
@learningJava4ds Because time is limited, I'm also doing this in my free time so if you can help fixing bugs please open a Pull Request, that would be more usefull.

**Comment by BlackIkeEagle** [comment]
@s-c-p So I'm doing the following:

~~~
$ sudo pip3 install komodo-python3-dbgp
$ pydbgp -d 127.0.0.1:9000 test.py
~~~

The debugger connects properly:
![screenshot_20180325_114539](https://user-images.githubusercontent.com/293691/37873688-1371583c-3022-11e8-8cde-da5b9e4f0456.png)

I can properly step to main():
![screenshot_20180325_114616](https://user-images.githubusercontent.com/293691/37873691-27e71b8a-3022-11e8-9b58-65d8c1346098.png)

I can step into main():
![screenshot_20180325_114650](https://user-images.githubusercontent.com/293691/37873700-3cc8113a-3022-11e8-8429-ed15f6c0a96d.png)

Eventually I end up having an error stating the debugger is in interactive mode and that is not supported:
![screenshot_20180325_114744](https://user-images.githubusercontent.com/293691/37873711-68289476-3022-11e8-9630-10b778429f01.png)

**Comment by BlackIkeEagle** [comment]
Closing because no further feedback
