### ISSUE TITLE
There is always show "Vdebug is not running" when I quit vim

### ISSUE THREAD

**Issue by markwu** [vim-vdebug/vdebug#341]
I just upgrade my Vdebug to master branch and without any configurations. When I quit vim, it always shows "Vdebug is not running" message, can I get rid of it?

Weird, this message never shows ii Vdebug v1.

I tried Vdebug master branch inside macvim/neovim, all of them have this issue.

**Comment by BlackIkeEagle** [comment]
This ca be removed but its not really a bug. The output is given because if you close vim we must make sure everything is shut down.

**Comment by markwu** [comment]
Ah, I see. Thanks. Since it is not a bug, the message is okay for me, just a little annoying.

**Comment by BlackIkeEagle** [comment]
I'll check if this could be handled more properly

**Comment by markwu** [comment]
Weird, this issue seems come back again. After recent update, I see `Vdebug is not running` again on vim exit.
