### ISSUE TITLE
Other variables in scope of a different stacktrace level?

### ISSUE THREAD

**Issue by kviolka** [vim-vdebug/vdebug#348]
In PHPstorm, when I'm on a breakpoint I can click a lower entry point in the stack trace to see the variables there. Is this something vdebug can do, maybe in future?

**Comment by BlackIkeEagle** [comment]
@kviolka you mean something like what the content was of a variable before, even if it is not within the scope of the method you are in and have the breakpoint triggered?

I would have to lookup if xdebug supports that kind of behaviour. Then it would be possible.

**Comment by kviolka** [comment]
Yes, In PHPstorm I can see the variables in different scopes when I click thhrough the stackstrace. I need this quite often to find out how I got to a problem. BTW Thank you so much for working on vdebug! :) Do you have a donation address?

**Comment by BlackIkeEagle** [comment]
This is now available thanks to #413
