### ISSUE TITLE
Cannot start debugger

### ISSUE THREAD

**Issue by king-c** [vim-vdebug/vdebug#351]
Hello,

I am having an issue starting the debugger.

Steps to reproduce

:VdebugOpt debug_file ~/vdebug.log
:VdebugOpt debug_file_level 2
F5

Log output

- [Debug] {Fri 20 2018 17:48:34} Started
- [Debug] {Fri 20 2018 17:48:34} Listening on port 9001
- [Debug] {Fri 20 2018 17:48:35} Error: (<class 'socket.gaierror'>, gaierror(-3, 'Temporary failure in name resolution'), <traceback object at 0x7ff1235c05c8>)
- [Debug] {Fri 20 2018 17:48:35} Stopping server
- [Debug] {Fri 20 2018 17:48:35} Finishing socket server

vimrc config

let g:vdebug_options= {
     \   "port" : 9001,
     \   "server" : '',
     \   "timeout" : 30,
     \   "on_close" : 'detach',
     \   "break_on_open" : 1,
     \   "max_children" : 128,
     \   "ide_key" : 'docker',
     \   "path_maps" : {
     \       '/var/www/app/': '/srv/Projects/'
     \   },
     \   "debug_window_level" : 0,
     \   "debug_file_level" : 0,
     \   "debug_file" : "~/vdebug.log",
     \   "watch_window_style" : 'expanded',
     \   "marker_default" : 'X',
     \   "marker_closed_tree" : '▸',
     \   "marker_open_tree" : '▾'
     \}
 " }

Any ideas where I am going wrong?

I have checked and I do have python support in vim.

vim --version | grep python
+cryptv          +linebreak       -python          +vreplace
+cscope          +lispindent      +python3         +wildignore
Linking: gcc   -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl     -L/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu -lpython3.6m -lpthread -ldl -lutil -lm

Thanks

**Comment by BlackIkeEagle** [comment]
@king-c I don't seem to be able to reproduce your issue with all the options you have provided. I think it's something local to your machine maybe that was blocking port 9001 or similar. Closing now, if you encounter this again, you can reopen this issue or create a new issue with a reference to thisone.
