### ISSUE TITLE
Ability to configure active windows

### ISSUE THREAD

**Issue by haringsrob** [vim-vdebug/vdebug#354]
Would it be possible to configure which panes are active on start?

For me I would like there to be just the variable window and optional toggle of the stack trace. 
The debugger stack (3rd window) does not need to be as big by default?

**Comment by BlackIkeEagle** [comment]
@haringsrob you could use 'window_arrangement': ['DebuggerWatch', 'DebuggerStatus']. There might be a need to add triggers to open the other windows

**Comment by BlackIkeEagle** [comment]
If someone makes a PR for this I'll take it, but going to close this because I think the layout configuration gives a nice way to choose how you want to use the debugger
