### ISSUE TITLE
Support for NodeJS 8 and above?

### ISSUE THREAD

**Issue by kristijanhusak** [vim-vdebug/vdebug#356]
Hi,

are you planning to add a support for newer NodeJS?

**Comment by kristijanhusak** [comment]
As described where?

In VDebugSetUp docs i saw that only node 0.10.x is supported, which is now really an old version (Latest is 10.0.x). I tried debugging node 8.7.0 with `--inspect` flag, but that doesn't work, it didn't detect it.

**Comment by BlackIkeEagle** [comment]
@krisrijanhusak I'll look into it, first thing I found is that you can use komodo-dbgp to debug nodejs. `npm install komodo-debug -g`. I still have to check if that works properly

**Comment by kristijanhusak** [comment]
I tried, but it threw this error:
```
Error: Cannot find module '_debugger'
```

**Comment by BlackIkeEagle** [comment]
@kristijanhusak I'll have to look into it

**Comment by BlackIkeEagle** [comment]
Thanks for checking it out btw

**Comment by Garethp** [comment]
@BlackIkeEagle It looks like this is a problem with komodo, but the posts on their forum didn't get turned into an issue on their Github until April this year, but its progress can be tracked [here](https://github.com/Komodo/KomodoEdit/issues/3749). It looks like node doesn't implement dbgp debugging, but rather Chromes V8 Inspector, which has its own protocol over a websocket conncetion. I don't think there's anything that can be done about this issue

**Comment by BlackIkeEagle** [comment]
Will have to update the documentation that node is no longer properly supported

**Comment by BlackIkeEagle** [comment]
In conclusion, it does not look like anyone is trying to get dpgp support working for newer versions of NodeJS. Even komodo IDE where the support initially started does no longer support dbgp for NodeJS debugging but relies on the v8 devtools for debugging.
