### ISSUE TITLE
BreakpointRemove * failure when clearing all breakpoints

### ISSUE THREAD

**Issue by bendoh** [vim-vdebug/vdebug#358]
`BreakpointRemove *` causes me to get the following message:

`RuntimeError: dictionary changed size during iteration`

And the breakpoints aren't cleared from the BreakpointWindow.

I can clear individual breakpoints with `:BreakpointRemove <id>`, but it's tedious when I just want to clear them all. I think it's an error in the python.

**Comment by lucc** [comment]
This should be fixed by #371

**Comment by bendoh** [comment]
Looks good!
