### ISSUE TITLE
When I press F3 it convert letters to uppercase instead of step in.

### ISSUE THREAD

**Issue by mota57** [vim-vdebug/vdebug#359]
As I said you can see the results in the image

![image](https://user-images.githubusercontent.com/7569989/40283088-f01339a4-5c46-11e8-9061-a370a39edcd2.png)

**Comment by lskegg-trulia** [comment]
I had the same issue but resolved with help from this webpage just today: http://vim.wikia.com/wiki/Mapping_fast_keycodes_in_terminal_Vim

Here's an excerpt from my .vimrc:
" KEYBINDINGS!
set <S-F1>=^[[23~
set <S-F2>=^[[24~
set <S-F3>=^[[25~
set <S-F4>=^[[26~
set <S-F5>=^[[28~
set <S-F6>=^[[29~
set <S-F7>=^[[31~
set <S-F8>=^[[32~
set <S-F9>=^[[33~
set <S-F10>=^[[34~
set <S-F11>=^[[23~
set <S-F12>=^[[24~
let g:vdebug_keymap = { "run" : "<S-F5>", "run_to_cursor" : "<S-F9>", "step_over" : "<S-F8>", "step_into" : "<S-F3>", "step_out" : "<S-F4>", "close" : "<S-F6>", "detach" : "<S-F7>", "set_breakpoint" : "<S-F10>", "get_context" : "<S-F11>", "eval_under_cursor" : "<S-F12>" }

I'm actually using Shift+Function keys for the bindings, but creating them without shift is the same method. Note, you cannot simply copy & paste these into your .vimrc. You must create the keycodes that bind to your function keys by typing Ctrl+V to enter the special highlighted characters of ^[ while editing your .vimrc inside vim, for example inside the string "^[[23~" you'd type <Ctrl-V>[23~.

Hope this gets you going.
