### ISSUE TITLE
Possible Layout Improvement?

### ISSUE THREAD

**Issue by Garethp** [vim-vdebug/vdebug#360]
Hey, I just updated my fork of vdebug with the latest current version, and I went ahead and applied my own tweaks the layout (Super easy thanks to the new windows_arrangement option), and I was wondering if you thought it might be worth trying to bring upstream? Here's a picture of what my layout looks like

![screen shot 2018-05-23 at 13 25 56](https://user-images.githubusercontent.com/709912/40424235-e7d1baf2-5e8c-11e8-9190-2a6e570651de.png)

Basically, it takes inspiration from PHPStorm and tries to minimize the space taken up by the debug window. I'm considering having an option to keep it on the left with the new Vim 8.1 processes, and just having the run being a small window at under status, as opposed to a Tmux view.

I think even if you prefer keeping it on the left, it might be worth seeing if the status window can be reduced. Personally I think you could realistically keep the status window to a single line either way. 

As a request, if you could add a height and width option for windows in the config, that would mean that the actual window layout would be doable without modifying the plugin to set the height and width of windows. 

Anyway, let me know your thoughts

**Comment by BlackIkeEagle** [comment]
I like the 1 line status, although I'm so used to the vdebug defaults it doesn't bother me.
If it would be possible to have the layout fully configurable that would be the best, then you could just setup your preferred layout in your vimrc

**Comment by Garethp** [comment]
If you add window height and widths as configuration items then I could provide this whole layout as a configuration example (Apart from the changes to what text is displayed in the status line)

**Comment by BlackIkeEagle** [comment]
Added it to the 2.1 project, so I'll try to fit it in there

**Comment by Taluu** [comment]
Hey, could there be anyway for you make a PR with your changes @Garethp ? I just cherry-picked it, and there's not much conflicts so shouldn't this be mergeable quickly ?

**Comment by phatsk** [comment]
@Taluu I know this was a while ago, but I just tried @Garethp 's better-layout and I have to say I really like it. I made a PR for the `better-layout` branch, although it may be better to do `master` to `master`? Let me know if this is at all viable: https://github.com/vim-vdebug/vdebug/pull/401

**Comment by Taluu** [comment]
Yep I've been using his layout for a while now. :}
