### ISSUE TITLE
Missing from documentation: start vi from directory, where your script resides

### ISSUE THREAD

**Issue by jm009** [vim-vdebug/vdebug#363]
I followed the documentation from
vdebug/doc/Vdebug.txt

I came to the point, that my php command line script stopped after start, but vi did not display the source code.

After I found out, that I have to start vi from the directory, where the script resides, it works.
This essential information is missing from vdebug/doc/Vdebug.txt.

**Comment by BlackIkeEagle** [comment]
@jm009 could you specify where you should add it in the documentation? I'm going to assume you are doing local debugging.

**Comment by jm009** [comment]
Chapter _4.1 Starting the debugger_ would be fine.

**Comment by BlackIkeEagle** [comment]
Feel free to open a PR @jm009

**Comment by jm009** [comment]
https://github.com/vim-vdebug/vdebug/pull/364
:-)

**Comment by BlackIkeEagle** [comment]
@jm009 great, really appreciate you took the time :+1:
