### ISSUE TITLE
disable "Force break on first line"

### ISSUE THREAD

**Issue by vivoconunxino** [vim-vdebug/vdebug#367]
Is it possible? I can't find a way to disable it. I'd like it to stop only at some specific breakpoint

**Comment by BlackIkeEagle** [comment]
https://github.com/vim-vdebug/vdebug/blob/master/doc/Vdebug.txt#L896

```
let g:vdebug_options = {
    \'break_on_open': 0
\}
```

↑ Should do it

**Comment by vivoconunxino** [comment]
Thanks, and sorry for the silly question. I focused more on google :'/
