### ISSUE TITLE
Error after upgrading vim to 8.1

### ISSUE THREAD

**Issue by anoopd** [vim-vdebug/vdebug#368]
Hi i am getting the error 

    Error detected while processing /Users/anoopd/.vim/plugged/vdebug/plugin/vdebug.vim:
    line   39:
    /must>not&exist/foo:1: DeprecationWarning: the imp module is deprecated in favour of importlib;

Please have a look

**Comment by BlackIkeEagle** [comment]
Please have a look here: https://github.com/vim-vdebug/vdebug/issues/366 its a vim issue
