### ISSUE TITLE
Vdebug  debugging NodeJS

### ISSUE THREAD

**Issue by WebWorkDeveloper** [vim-vdebug/vdebug#370]
Hi, I have some problems with connecting inspect agent in my VIM.
I am work with NodeJS on MacOS 10.13.5

I have npm@5.6.0 and node@8.11.3

I check :help vdebug

run `npm install komodo-debug -g`

run `run node-dbgp -h 127.0.0.1 -p 9000 myscript.js` ---> `(node:97350) [DEP0062] DeprecationWarning: `node --debug` and `node --debug-brk` are invalid. Please use `node --inspect` or `node --inspect-brk` instead.`

All right, I use `node --inspect=9000`

In my VIM how I press F5 I see `Vdebug will wait for a connection in the background`

**Comment by mstuessy** [comment]
Why is this issue closed? Is there a solution?

**Comment by nmercado1986** [comment]
Can we reopen this issue?
Getting vdebug to debug NodeJS without the need to install a separate plugin for node debugging would be great.
