### ISSUE TITLE
ml_get errors; 

### ISSUE THREAD

**Issue by bendoh** [vim-vdebug/vdebug#381]
Vdebug 2.0.0  @ 2ebf27b1ffb6752f0ba6cf4ec6be0a7498897d48

I'm trying to figure out how to reliably reproduce this issue, but there seems to be a problem in management of the DebuggerStatus window. At some point, Vdebug enters a state where any command triggers errors akin to this:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/bdoherty/.vim/bundle/vdebug/python3/vdebug/debugger_interface.py", line 47, in run
    self.session_handler.run()
  File "/Users/bdoherty/.vim/bundle/vdebug/python3/vdebug/session.py", line 65, in run
    self.listen()
  File "/Users/bdoherty/.vim/bundle/vdebug/python3/vdebug/session.py", line 42, in listen
    self.start_listener()
  File "/Users/bdoherty/.vim/bundle/vdebug/python3/vdebug/session.py", line 49, in start_listener
    self.ui().set_status("listening")
  File "/Users/bdoherty/.vim/bundle/vdebug/python3/vdebug/ui/vimui.py", line 170, in set_status
    self.windows.status().set_status(status)
  File "/Users/bdoherty/.vim/bundle/vdebug/python3/vdebug/ui/vimui.py", line 634, in set_status
    self.insert("Status: %s" % str(status), 0, True)
  File "/Users/bdoherty/.vim/bundle/vdebug/python3/vdebug/ui/vimui.py", line 460, in insert
    lambda: self.command(lineno))
  File "/Users/bdoherty/.vim/bundle/vdebug/python3/vdebug/ui/vimui.py", line 345, in insert
    self._buffer[:] = remaining_buffer
vim.error: Vim:E315: ml_get: invalid lnum: 81
```

Where the error is always about `ml_get` caused by `set_status`

The only way I can stop this from happening is to restart vim.

**Comment by bendoh** [comment]
Closing this as it seems to be a bug in vim rather than this plugin.

**Comment by BlackIkeEagle** [comment]
Thanks for the info. Really appreciate it.

**Comment by bendoh** [comment]
I just updated vim to 8.1.350 and the problem has not reproduced. Great work on the plugin!

**Comment by bendoh** [comment]
Reopening this as I'm still encountering it frequently. Once I figure out a reliable reproduction method, I will share it.

**Comment by lucc** [comment]
I also that there can be some improvement about window management. Especially as the vim python bindings offer a class for buffers and windows and tabs and so on but we keep our own ids around.  But then again that would be a major rewrite of window management of vdebug so it seems like a lot of work...

**Comment by bendoh** [comment]
Yeah, it's definitely a big chunk of work, but I'm encountering frequent bugginess around that, and I think it'd be worth the investment. It looks like it's really a matter of using the `[:] = []` python expression on a hidden buffer, so maybe it's as simple as ensuring that the buffers aren't hidden when that happens, though I do think it's more of a vim-level issue

**Comment by BlackIkeEagle** [comment]
@bendoh ml_get errors, are you having these on Linux, Mac or Windows

**Comment by bendoh** [comment]
I just updated to `d3d1672` with @lucc's changes, and it's pretty broken. The windows don't appear in the right place at all. Did this get tested?

My issues occur on a mac, with the following vim:

```
 % vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep  6 2018 13:43:23)
macOS version
Included patches: 1-350
... +python3 -python ...
```

This problem frequently occurs when I'm using my php testing tool along with Vdebug, where I often hide the various Debugger buffers during a session to navigate the code. Subsequent invocations of Vdebug cause this problem repeatedly until I can reset its state or just restart vim.

I suspect the problem here is mostly to do with a failure to detect when buffers have been hidden, because the windowing code switches between instances of `HiddenBuffer`, where the buffer is just a string, and `VimBuffer`, where it appears to be tied to an actual buffer object. This is where the bug occurs: when the VimBuffer actually refers to a hidden buffer, and assignments to `_buffer[:]` trigger the `ml_get` issue because that operation is invalid on a hidden buffer (though, imho, it shouldn't be!)

Possibly related, if I start a debugging session, and then go to one of the Debugger buffers, and attempt to delete it, I get a pretty bleak message:

```

Error detected while processing BufWinLeave Autocommands for "DebuggerStack":
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/bdoherty/.vim/bundle/vdebug/python3/vdebug/debugger_interface.py", line 101, in mark_window_as_closed
    self.session_handler.ui().mark_window_as_closed(window)
  File "/Users/bdoherty/.vim/bundle/vdebug/python3/vdebug/ui/vimui.py", line 105, in mark_window_as_closed
    self.windows.window(name).mark_as_closed()
  File "/Users/bdoherty/.vim/bundle/vdebug/python3/vdebug/ui/vimui.py", line 441, in mark_as_closed
    self.destroy()
  File "/Users/bdoherty/.vim/bundle/vdebug/python3/vdebug/ui/vimui.py", line 495, in destroy
    vim.command('bwipeout %s' % self.name)
vim.error: Vim(bwipeout):E937: Attempt to delete a buffer that is in use
```

If I go to the `DebuggerLog` window and load `DebuggerStack` buffer instead, I start getting the `ml_errors`, too. There's definitely some funkiness in tracking the windows. I don't think it's too bleak to figure out, but it might require rewriting parts of the UI file.

**Comment by BlackIkeEagle** [comment]
Something went wrong there, the python cleanup changes were resetted
