### ISSUE TITLE
No option with key background_listener

### ISSUE THREAD

**Issue by FatBoyXPC** [vim-vdebug/vdebug#387]
I'm not sure when the last time I used xdebug was (probably a few months ago), but at some point something broke:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/james/.vim/plugged/vdebug/python3/vdebug/debugger_interface.py", line 47, in run
    self.session_handler.run()
  File "/home/james/.vim/plugged/vdebug/python3/vdebug/session.py", line 65, in run
    self.listen()
  File "/home/james/.vim/plugged/vdebug/python3/vdebug/session.py", line 42, in listen
    self.start_listener()
  File "/home/james/.vim/plugged/vdebug/python3/vdebug/session.py", line 45, in start_listener
    self.listener = listener.Listener.create()
  File "/home/james/.vim/plugged/vdebug/python3/vdebug/listener.py", line 12, in create
    if opts.Options.get('background_listener', int):
  File "/home/james/.vim/plugged/vdebug/python3/vdebug/opts.py", line 31, in get
    raise OptionsError("No option with key '%s'" % name)
vdebug.opts.OptionsError: No option with key 'background_listener'
```
Vim 8.1
Arch linux (up to date)
Python 3.7
PHP 7.2.12

vimrc settings:
```
let g:vdebug_options = {"break_on_open": 0}
```

**Comment by zhumingyu** [comment]
@FatBoyXPC hi,guy!can you press F5 and run?

**Comment by FatBoyXPC** [comment]
That's what gave me the error :stuck_out_tongue:

**Comment by zhumingyu** [comment]
Do you debug python with vdebug?

**Comment by FatBoyXPC** [comment]
PHP, xdebug

**Comment by FatBoyXPC** [comment]
It appears as though I don't get this error anymore after a reboot.

**Comment by BlackIkeEagle** [comment]
Great @FatBoyXPC that makes it easy :grinning:

**Comment by JulesFaucherre** [comment]
Hello, I have the exact same issue but restarting my computer doesn't work
I am using vdebug to debug php with xdebug
When I run `:VdebugStart` a first time I get `No option with key 'autostart'` but if I run it again I always get `No option with key 'background_listener'`

Here is my config :

NVIM v0.5.0-dev+1007-g9223d1450
Python 3.9.1
Ubuntu 20.04.1 LTS
PHP 7.4.13 (cli) (built: Nov 28 2020 06:24:59) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.13, Copyright (c), by Zend Technologies
    with Xdebug v3.0.2, Copyright (c) 2002-2021, by Derick Rethans

I have been able to reproduce the problem with a minimalistic .vim/init.vim : 
```
call plug#begin('~/.config/vim/plugins')

Plug 'vim-vdebug/vdebug'

call plug#end()

let g:python_host_prog = "/path/to/python2"
let g:python3_host_prog = "/path/to/python3"
```


Maybe you want me to create an other issue
