### ISSUE TITLE
A clear answer should be given to "Does vdebug work on python3 code?"

### ISSUE THREAD

**Issue by AbsurdMagpieScrutinies** [vim-vdebug/vdebug#388]
Over 
* all the internets, 
* the vdebug help pages, 
* this vim-debug github repository, 
* neovim -vs- vim forum discussion re: vdebug;;
* different vim and neovim versions

and there is no statement - at all, let alone a clear answer - to this one question:

*Can vdebug be made to work on on python3 code?*
       
This is not "has vdebug been programmed to use python3?". It is about what code, python3 code, can or can not vdebug work with. 

If the answer is "yes", then, great. 
If the answer is "no", then, great: it'd be good to know.  

I have 
* the very latest neovim (version 0.3.0), with python3 and python2 support 
* I have redownloaded the latest Komodo-PythonRemoteDebugging-11.1.0-91033-linux-x86_64
* I have done `pip3 install --update python3-neovim`
* deleted and reinstalled vdebug

and it won't work. However, other people have got it to work on python3 code, it seems. 

I want to know if I am trying something that won't work. Others will want to know if they can get vdebug to work on python3 code.

**Comment by BlackIkeEagle** [comment]
The short answer will be "no". I see the activestate dbgp implementation has no python3 support at the time. So we could consider it unmaintained? Even the forks I could find do not support python3.
