### ISSUE TITLE
Support disabling/enabling a breakpoint.

### ISSUE THREAD

**Issue by ahakanbaba** [vim-vdebug/vdebug#393]
Turning on and off breakpoints is quite a common operation. Could we support a dedicated disable enable breakpoint operation ? 

As far as I know, one can only delete a breakpoint today.  If the user wants to temporarily not use a breakpoint, she needs to remove it. Later on once she wants to break at the same spot, she needs to find the same line and create a new breakpoint. The id of the breakpoint will also be distinct. This is quite cumbersome. 

Instead a much simpler enable/disable breakpoint operation would make the workflow much simpler. 
One could have `BreakpointEnable <ID>` `BreakpointDisable <ID>` commands and the BreakpointWindow would have a new column showing enabled,disabled state. 

In addition, we could support `e` `d` key bindings if the vim cursor is on the BreakpointWindow. `e` would enable the breakpoint under cursor, similarly `d` would disable. 

Something similar also exists in gdb, pdb debuggers. 

I unfortunately do not know whether the dbgp protocol or xdebug has the necessary support for this. Can anyone comment on possible implementation ?

**Comment by ahakanbaba** [comment]
Looking at the [breakpoints section](https://github.com/derickr/dbgp/blob/master/debugger_protocol.rst#id49) in dbgp. I do not see breakpoint_enable or disable.
 
There are only 
```
7.6.1 breakpoint_set
7.6.2 breakpoint_get
7.6.3 breakpoint_update
7.6.4 breakpoint_remove
7.6.5 breakpoint_list
```
So if we want to support enable/disable  of a breakpoint, we may 
1. Modify dbgp and xdebug
2. Maintain some state on the vim-vdebug side. 

Not sure whether either of these are feasible or good ideas.

**Comment by Taluu** [comment]
I think it should be done on the vim-debug side, as patching xdebug / dbgp would be quite a mess I think.

But 👍 for the shortcuts on the breakpoint window.

**Comment by ahakanbaba** [comment]
May I ping the maintainers as far as I can guess ? @BlackIkeEagle  @lucc  ? 
What is your reaction to this ?

**Comment by lucc** [comment]
Patching xdebug or dbgp is not in the scope of this project. Whoever wants to do something like this can obviously go upstream and do it.

I think for vdebug we should plan and work with the existing protocol. So it seems that the only solution is to keep some state of "disabled" (but officially deleted) breakpoints in vdebug. Now if you want persistence of ids we need to check how vdebug constructs its ids. If they are provided by dbgp we might have a problem.

Some nice mappings for the breakpoint window are useful on their own and could be implemented also independently.

Generally I understand that the requested feature is useful for vdebug and would say "PRs welcome".

**Comment by Garethp** [comment]
Perhaps I'm missing something, but doesn't the protocol already support this? The dbgp documentation for the [attributes of a breakpoint](https://xdebug.org/docs-dbgp.php#breakpoints) has a property for a breakpoint called `state`, which can be set to `enabled` or `disabled`, so you'd just toggle the breakpoint using `breakpoint_update`.
