### ISSUE TITLE
F11 endup with a missing `context_id`

### ISSUE THREAD

**Issue by dave2309** [vim-vdebug/vdebug#395]
I have been using vdebug for a while now, works great. I actually thank you for it :p.
I have though a little something, might be about configuration but not sure. 
When I try to get back from a "vdebugEval" to global variables (F11), I got an python error about not having `context_id`. Any clue what to look for? Or how can I test that?
"TypeError: run() missing 1 required positional argument: 'context_id'" ,                                                      

Thanks for your great work, could not work without it
Dave

**Comment by dave2309** [comment]
First error message is (after hitting F11)
`An error occured: <class 'TypeError'>
Traceback (most recent call last):
  File "/home/david.tourrel/.vim/bundle/vdebug/python3/vdebug/event.py", line 522, in dispatch_event
    Dispatcher.events[name](self.__session_handler).run(*args)
TypeError: run() missing 1 required positional argument: 'context_id'`

**Comment by dave2309** [comment]
Second error sometimes closing the first one
`Error detected while processing BufWinLeave Autocommands for "DebuggerLog":
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/x/.vim/bundle/vdebug/python3/vdebug/debugger_interface.py", line 101, in mark_window_as_closed
    self.session_handler.ui().mark_window_as_closed(window)
  File "/x/.vim/bundle/vdebug/python3/vdebug/ui/vimui.py", line 108, in mark_window_as_closed
    self.windows.window(name).mark_as_closed()
  File "/xl/.vim/bundle/vdebug/python3/vdebug/ui/vimui.py", line 439, in mark_as_closed
    self.destroy()
  File "/xl/.vim/bundle/vdebug/python3/vdebug/ui/vimui.py", line 498, in destroy
    vim.command('bwipeout %s' % self.name)
vim.error: Vim(bwipeout):E937: Attempt to delete a buffer that is in use
`

**Comment by dave2309** [comment]
I try to run without a minimal `vimrc` containing only `vdebug` 
OS: ubuntu 16.04
vim: `VIM - Vi IMproved 8.1 (2018 May 18, compiled Jan 28 2019 15:24:39)
Included patches: 1-837
Modified by jonathon.fernyhough@york.ac.uk
Compiled by jonathon.fernyhough@york.ac.uk
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               +extra_search      +mouse_netterm     +tag_old_static
+arabic            +farsi             +mouse_sgr         -tag_any_white
+autocmd           +file_in_path      -mouse_sysmouse    +tcl
+autochdir         +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
+balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
+browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +textprop
+byte_offset       -hangul_input      +num64             +timers
+channel           +iconv             +packages          +title
+cindent           +insert_expand     +path_extra        +toolbar
+clientserver      +job               +perl              +user_commands
+clipboard         +jumplist          +persistent_undo   +vartabs
+cmdline_compl     +keymap            +postscript        +vertsplit
+cmdline_hist      +lambda            +printer           +virtualedit
+cmdline_info      +langmap           +profile           +visual
+comments          +libcall           -python            +visualextra
+conceal           +linebreak         +python3           +viminfo
+cryptv            +lispindent        +quickfix          +vreplace
+cscope            +listcmds          +reltime           +wildignore
+cursorbind        +localmap          +rightleft         +wildmenu
+cursorshape       +lua               +ruby              +windows
+dialog_con_gui    +menu              +scrollbind        +writebackup
+diff              +mksession         +signs             +X11
+digraphs          +modify_fname      +smartindent       -xfontset
+dnd               +mouse             +startuptime       +xim
-ebcdic            +mouseshape        +statusline        +xpm
+emacs_tags        +mouse_dec         -sun_workshop      +xsmp_interact
+eval              +mouse_gpm         +syntax            +xterm_clipboard
+ex_extra          -mouse_jsbterm     +tag_binary        -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/mirclient -I/usr/include/mircore -I/usr/include/mircookie -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Wdate-time  -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.22/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu -lpython3.5m -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lieee -lm -lruby-2.3 -lpthread -lgmp -ldl -lcrypt -lm`

**Comment by BlackIkeEagle** [comment]
@dave2309 I'm assuming this is consistent => VdebugEval and then F11 -> stacktrace

**Comment by dave2309** [comment]
Yes consistent

**Comment by dave2309** [comment]
Fix does work great thanks!
