### ISSUE TITLE
My DebuggerStatus is empty when i debug php

### ISSUE THREAD

**Issue by yunxi177** [vim-vdebug/vdebug#398]
![](http://pic.artacode.com/Screenshot%20from%202019-05-02%2018-14-52.png)

**Comment by lucc** [comment]
There seems to be another DebuggerStatus window on the right. That one is not empty. It also lists two maps for `<F6>` one for starting and one for stopping the debugger.  Did you add some key mappings? can you check your maps with `:map <F6>`?

**Comment by yunxi177** [comment]
Thanks for your help, i didn't add key mappings. this  is `map <f6>`  return 
``` 
<F6>        * :python3 debugger.close()<CR>                    3,1           All
```
The question I'm facing now is  I can't see my code and  i don't know the step running which line.

**Comment by lucc** [comment]
Ok with the info right now it is impossible to help you any further. Try to do some debugging of the problem and add more info to this issue (like the stuff one normally puts into a bug report anyways: your system, versions how you install and start vdebug, log files etc).

**Comment by BlackIkeEagle** [comment]
@yunxi177 are you still facing problems? first thing I would think about is "is your path mapping correct", because that could cause it for you not to see your code.
