### ISSUE TITLE
Vim remote xdebug into docker container

### ISSUE THREAD

**Issue by romanhandke** [vim-vdebug/vdebug#420]
Hey everyone. I am currently trying to set up my nVim to remote debug PHP which is run inside a Docker container. By this point I am almost certain I am overlooking something hilariously obvious but I have been banging my head against this for so long I can't seem to figure it out.

> edit: In the end it was a problem with my firewall configuration :(
Before I found that I switched to the php:apache image. Then I installed xdebug and added my custom xdebug.ini via Dockerfile so if anyone stumbles upon this, the way below should still work (I'll edit some parts) but is not what finally worked for me.

### Docker Setup

To make it easy on me (at least that's what I thought starting out) I grabbed this neat docker image:
> webdevops/php-apache-dev
> https://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-apache-dev.html

which makes it easy to set some of the xdebug settings.

My docker-compose yml looks like this:

    version: "3.6"
    services:
      x_web:
      image: webdevops/php-apache-dev
      restart: always
      volumes:
        - ../public:/var/www/html
      ports:
        - '8080:80'
      container_name: x_web
      environment:
        XDEBUG_REMOTE_AUTOSTART:        1
        XDEBUG_REMOTE_CONNECT_BACK:     0
        XDEBUG_REMOTE_HOST:             172.17.0.1
        XDEBUG_REMOTE_PORT:             9000
        WEB_DOCUMENT_ROOT:              /var/www/html

> edit: In the end I switched connect_back back on and it did work just fine.

The environment variables:
* activate the remote_autostart
* deactivate the remote_connect_back so that it does not override the remote_host
* set the standard port which vdebug is expecting

To find out the IP my container would find my host under I did:

    ip a | grep docker
    4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0

Since I did not specify a network for the service it will attach itself to docker_default which is bridged and thus able to reach the host - at least I can successfully ping the address :)

Since I am ultimately planning on making this work on some other dev compose environments, I set the web root to what I would use there. This is also where I have mapped the volume to which contains the script I'd eventually like to debug.

### nVim Setup
This is my nVim

    ➜  ~ vim --version
    NVIM v0.3.7
    Build type: Release
    LuaJIT 2.1.0-beta3
    Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-8dKHat/neovim-0.3.7=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-8dKHat/neovim-0.3.7/build/config -I/build/neovim-8dKHat/neovim-0.3.7/src -I/usr/include -I/build/neovim-8dKHat/neovim-0.3.7/build/src/nvim/auto -I/build/neovim-8dKHat/neovim-0.3.7/build/include
    Compiled by team+vim@tracker.debian.org

    Features: +acl +iconv +jemalloc +tui 
    See ":help feature-compile"

       system vimrc file: "$VIM/sysinit.vim"
      fall-back for $VIM: "/usr/share/nvim"

    Run :checkhealth for more info`

Since Python is needed, here is what :checkhealth has to say on that account:

    ## Python 3 provider (optional)
      - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
      - INFO: Executable: /usr/bin/python3
      - INFO: Python version: 3.6.8
      - INFO: pynvim version: 0.3.2
      - OK: Latest pynvim is installed.

From :help Vdebug I gathered I'd have to add the following to my nvim 

    " xDebug Settings
    if !exists('g:vdebug_options')
      let g:vdebug_options={}
    endif
    let g:vdebug_options.path_maps = {"/var/www/html": "/home/roman/projects/xdebug/public"}
    let g:vdebug_options.server = ""

> edit: not sure this was really necessary since ...

So the remote dir matches the web root on the container and yes since I am not a creative person my test project is called xdebug. The docker-compose.yml file lies in xdebug/docker so that the volume entry should be fine as well.

### PHP

This is PHP running inside the container:

    root@b7820729e785:/etc/php/7.2/cli# php -v
    PHP 7.2.19-0ubuntu0.18.04.1 (cli) (built: Jun  4 2019 14:48:12) ( NTS )
    Copyright (c) 1997-2018 The PHP Group
    Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
        with the ionCube PHP Loader + ionCube24 v10.3.7, Copyright (c) 2002-2019, by ionCube Ltd.
        with Zend OPcache v7.2.19-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend Technologies
        with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans

I am aware that xdebug is not supposed to work with ionCube:
> https://xdebug.org/docs/install

But I do not get any errors in this regard

xDebug is up and running inside the container, too. Since this will get pretty long I'll attach the output of 
    php --info

in a separate file.
[phpinfo.txt](https://github.com/vim-vdebug/vdebug/files/3372524/phpinfo.txt)

### Were it all comes tumbling down

After all this setup I thought I was ready to go. I open the index.php file inside the dir that's matched to the web root and pressed <F5>:
> Vdebug will wait for a connection in the background 

Then I browsed to the page.

Since nothing happend I checked the remote_log:

    Log opened at 2019-07-09 10:39:02
    I: Connecting to configured address/port: 172.17.0.1:9000.
    E: Time-out connecting to client (Waited: 200 ms). :-(
    Log closed at 2019-07-09 10:39:02

So the container seems to be unable to reach the client, but I don't understand why.

Since it's a bridged network I thought I could do
    docker network inspect docker_default

and use the gateway as an address the container could reach the host under but to no avail.
[network_inspect.txt](https://github.com/vim-vdebug/vdebug/files/3372582/network_inspect.txt)

I'd really appreciate if someone could give me a nudge in the right direction. Cheers.

**Comment by BlackIkeEagle** [comment]
@romanhandke the solution to your problem was?

- docker gateway ip was incorrect? did you have to update the `XDEBUG_REMOTE_HOST` to another value?

**Comment by romanhandke** [comment]
@BlackIkeEagle sorry, it took me a while to see your question.

My problem was, that any incoming connection on Port 9000 was blocked by ufw ... so it was - after all - something dumb.

As I understand it XDEBUG_REMOTE_HOST is overruled by `XDEBUG_REMOTE_CONNECT_BACK` (if active) anyway and thus can be skipped.

My Xdebug config () simply consists of
    zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20160303/xdebug.so
    xdebug.remote_enable=1
    xdebug.remote_connect_back=1
    xdebug.remote_port=9000

`xdebug.remote_enable` Enables remote debuggin :)
`xdebug.remote_connect_back` allows xdebug to track my host system when I open the script I wish to  debug in my Browser (I use the Xdebug-Helper Browser addon)
`xdebug.remote_port` is the port on which my nVim expects the incoming connection
