### ISSUE TITLE
vim hangs on exit if vdebug was run

### ISSUE THREAD

**Issue by JasonWoof** [vim-vdebug/vdebug#423]
Reproduce:

debug something with vdebug (eg set a breakpoint, then set it to continue so the php/http process finishes)

close out of the debugger so I'm back to just editing a file.

quit vim

result: vim freezes and must be killed -11 by another terminal

request: vim should quit

workaround: if I press the vdebug "detach" and "close" keys before quitting then vim quits just fine. Maybe only one of these is required for the workaround to work.

**Comment by BlackIkeEagle** [comment]
@JasonWoof Thanks for your report, I can confirm this happens:

- start vim
- listen
- run php script
- press F5 to make the script contiue
- vdebug gets back in listening mode (with debug ui open)
- `:qa`
- hangs forever

**Comment by skotos** [comment]
I'm experiencing this myself. This is what I have found...

* $ vi index.php
* :autocmd VDebug 

> --- Autocommands ---
> Vdebug  VimLeavePre
>     *         python3 debugger.close()

* F5 (start debugger)
* :autocmd VDebug 

> --- Autocommands ---
> Vdebug  CursorHold
>     *         python3 debugger.start_if_ready()
> Vdebug  CursorHoldI
>     *         python3 debugger.start_if_ready()
> Vdebug  CursorMoved
>     *         python3 debugger.start_if_ready()
> Vdebug  CursorMovedI
>     *         python3 debugger.start_if_ready()
> Vdebug  FocusGained
>     *         python3 debugger.start_if_ready()
> Vdebug  FocusLost
>     *         python3 debugger.start_if_ready()
> Vdebug  VimLeavePre
>     *         python3 debugger.close()
> 

* F6 (stop debugger)
* autocmd VDebug

> --- Autocommands ---

And all the commands are **GONE** - including the one to close the debugger on VimLeavePre.

Now to find where it is being removed.

**Comment by skotos** [comment]
Found it.  Listener.py:59 is removing all autocmds after the listener closes. I see two ways of fixing this.

**FIX A:** Reinsert the original autocmd after Listener closes.

```diff
diff --git a/python3/vdebug/listener.py b/python3/vdebug/listener.py
index 1577590..2ac27fb 100644
--- a/python3/vdebug/listener.py
+++ b/python3/vdebug/listener.py
@@ -57,6 +57,7 @@ class BackgroundListener:
         if opts.Options.get("auto_start", bool):
             vim.command('augroup Vdebug')
             vim.command('autocmd!')
+            vim.command('autocmd VimLeavePre * python3 debugger.close()')
             vim.command('augroup END')
         self.__server.stop()
```

**FIX B:** Put the VimLeavePre autocmd in its own unique group so that it isn't abolished with the rest of the autocmds when the Listener closes.

```diff
diff --git a/plugin/vdebug.vim b/plugin/vdebug.vim
index 9eb9ead..b04a440 100644
--- a/plugin/vdebug.vim
+++ b/plugin/vdebug.vim
@@ -308,6 +308,8 @@ function! Vdebug_statusline()
 endfunction
 
 augroup Vdebug
+augroup END
+augroup VdebugOut
 autocmd VimLeavePre * python3 debugger.close()
 augroup END

``` 




I can do a PR for either.  Which would be best?

**Comment by lucc** [comment]
@skotos the second approach looks cleaner to me.

**Comment by skotos** [comment]
I agree with the second approach being cleaner. I've only started digging into the code so I'm not sure if anything destroys the debugger object. It is created in plugin/vdebug.vim:112 and is not destroyed in this file. I may have time tonight to have a closer look but I believe it persists till the end of vim. (anyone else know?)

**Comment by skotos** [comment]
Whilst a destructor is declared for DebuggerInterface, I see nowhere that del is called on the debugger object. I think it is safe to say that it is ok to keep the VimLeavePre autocmd active. I'll submit a PR for review. Cheers.
