### ISSUE TITLE
dots in watch window

### ISSUE THREAD

**Issue by cprn** [vim-vdebug/vdebug#425]
Hello,

First of all, I'm very happy with vdebug, keep up the good work!

The minor issue I'm having is while displaying context of complex objects in the watch window, it sometimes trims to "..." (three dots). Can this be configured so it would display all of the object properties?

![image](https://user-images.githubusercontent.com/6132708/64433706-4b2bbf80-d0bf-11e9-9eec-24788ffe54a6.png)

**Comment by mzagol** [comment]
By default, number of child elements is limited to 32. You can override it by setting `max_children` property to a value that's more appropriate for your project. For example:

`let g:vdebug_features = {"max_children": 128}`

**Comment by cprn** [comment]
Awesome, exactly what I was looking for, thank you!
