### ISSUE TITLE
Error starting Vdebug: <class 'UnicodeEncodeError'> in win7 os

### ISSUE THREAD

**Issue by determin1st** [vim-vdebug/vdebug#429]
![222](https://user-images.githubusercontent.com/16524081/66273913-3a26c780-e892-11e9-81f6-fa98d2600b3d.png)

looks like it happens at `.encode()` in `connection.py`..

**Comment by ossie-git** [comment]
I ran into something similar on a Ubuntu box.  The solution was to add the following two lines to my .vimrc file:

```
set encoding=utf-8
scriptencoding utf-8
```

**Comment by determin1st** [comment]
@ossie-git 

thanks, i've only recently managed to find some setting.. with windows os

`set encoding=utf-8`

will not work, you also need

`set renderoptions=type:directx`

for gvim...

**Comment by BlackIkeEagle** [comment]
@determin1st does your solution fix the issue? or does it need further investigation?

**Comment by determin1st** [comment]
@BlackIkeEagle oops, i did forget to test it :/ im pretty sure it will solve..

**Comment by BlackIkeEagle** [comment]
I'm going to close this because I think it is fixed
