### ISSUE TITLE
wrong version number in latest release

### ISSUE THREAD

**Issue by baptx** [vim-vdebug/vdebug#430]
The latest release 2.0.0 that can be downloaded on GitHub (https://github.com/vim-vdebug/vdebug/releases) indicates version 1.4.1 instead of 2.0.0 in the file `/plugin/vdebug.vim`.

**Comment by BlackIkeEagle** [comment]
https://github.com/vim-vdebug/vdebug/blob/204e5150fd7a50519cfc23fe1c61b90af0cd105f/plugin/vdebug.vim#L11 Missed that, its still like this in the current master, this is not actually a serious issue since its just a comment, but should get updated in the next release
