### ISSUE TITLE
Possibly missing comma

### ISSUE THREAD

**Issue by JJP7** [vim-vdebug/vdebug#438]
Hello, I am trying to debug python code and while I was doing so,
I tried to evaluate highlighted expressions in visual mode with ``<Leader>e`` but it was giving error messages saying:
``Traceback (most recent call last):``                                    
  ``File "<string>", line 1, in <module>``                                  
``AttributeError: 'DebuggerInterface' object has no attribute 'eval_visual'``
 
Also before this, I followed the fix in https://gist.github.com/3348076
and modified the client.py file accordingly as mentioned in the ```VdebugSetupPython```

I was then able to evaluate expressions with ``:VdebugEval``, but evaluating the highlighted text was not working....

So I grepped for the ``eval_visual`` attribute and I found in util.py:
``exclude = ["run", "close", "set_breakpoint", "enable_breakpoint", "disable_breakpoint",
               "toggle_breakpoint" "eval_visual"]``

There seems to be a missing comma ``,`` in between ``"toggle_breakpoint"`` and ``"eval_visual"``
After adding the comma, everything is working fine.

Here:
https://github.com/vim-vdebug/vdebug/blob/d150bb5a90bc92f79b138bcdd602b7e0f492fa53/python3/vdebug/util.py#L108

**Comment by JJP7** [comment]
I have created a pull request

**Comment by BlackIkeEagle** [comment]
Thanks :+1:
