### ISSUE TITLE
Does not break when multiple requests fired

### ISSUE THREAD

**Issue by mlapai** [vim-vdebug/vdebug#461]
Hi,

Lets say that im firing 2 consequtive requests from frontend application:
1. /something
2. /something-else

And i've set my breakpoint to debug first request code. If debugger gets another request after, he will just ignore my breakpoint that is set to debug first request (im guessing it does not stop because he gets new connection and probably resets debugging). Is it possible to force stop on breakpoint and stop script execution, and let the other requests execute if breakpoint is not set in their part of the code ?

**Comment by BlackIkeEagle** [comment]
Currently Vdebug does not support multiple debugging connections. I have to look into it what the behaviour is in your case

**Comment by BlackIkeEagle** [comment]
@mlapai I've tried to reproduce this and in my case the second request just continues without hitting the debugger, the first gets the connection

**Comment by BlackIkeEagle** [comment]
Currently there will be no changes regarding this, if you want to re-open later please do
