### ISSUE TITLE
Path_mapping not working in some cases

### ISSUE THREAD

**Issue by pjio** [vim-vdebug/vdebug#469]
If I set the path mapping after vim has started via the vdebug_options they will not be used for breakpoints:

```
" This stopped working for breakpoints:
let g:vdebug_options.path_maps = {"/app": "/home/user/local_source"}

" This seems to work like expected:
VdebugAddPathMap /app /home/user/local_source
```

I can debug with `break_on_open = 1` and the path_mapping is recognized, but a breakpoint will not use the mapped remote path.

I looked up the remote path in both the xdebug.remote_log and in `utils.py` -> `_create_remote(f)`.
The `path_maps` dict in `_create_remote(f)` is emtpy. If I set the path mapping in my global vimrc, it works.

I assume, the options are not reloaded before sending a breakpoint.

**Comment by BlackIkeEagle** [comment]
If you really want to use
`let g:vdebug_options.path_maps = {"/app": "/home/user/local_source"}`
you also should manually call
`:py3 debugger.reload_options()`

The supported way is making use of `VdebugPathMap` or `VdebugAddPathMap`

**Comment by pjio** [comment]
Thank you for the explanation. I reported it, because previously it was working with the global variable. Makes sense to use the new supported way!
