### ISSUE TITLE
Using vdebug with python virtual environments

### ISSUE THREAD

**Issue by j9** [vim-vdebug/vdebug#47]
Hello,

I'm trying to use vdebug on python project who's inside virtual-env, and am getting this error from pydbgp when run from withing virtual-env.

Traceback (most recent call last):
  File "./bin/pydbgp", line 71, in <module>
    import getopt
ImportError: No module named getopt

If pydbgp is run outside of the virtual-env of the project, the project specific packges installed in virtual-env are not found and pydbgp fails. When run from the same virtual-env as the project the above error is being raised.

pydbgp version information:
$ pydbgp --v
pydbgp Version 1.1.0 Revision #1 Change 118727

Version of Komodo remote debugger:
Komodo-PythonRemoteDebugging-7.1.3-74661-linux-x86_64.tar.gz

Although this may not be directly related to vdebug, it's related to usage of the tool. So any help or suggestions are welcome.

**Comment by sambonner** [comment]
Sorry to comment on such an old issue, but the way to achieve is not to follow the instructions in the help file for getting Vdebug working with python, but actually to try something like this - http://rofl.jobiroxa.com/2013/12/debugging-python-with-vim-in-virtualenv.html

Its much nicer as everything is installed via PIP and it will work with a virtualenv.
