### ISSUE TITLE
Error starting timeout

### ISSUE THREAD

**Issue by Mte90** [vim-vdebug/vdebug#484]
![Screenshot_20200914_171549](https://user-images.githubusercontent.com/403283/93104352-06613e00-f6ae-11ea-82c6-be2f72b65f7a.png)

I am getting this error maybe is connected to #403?

The log when this error is happening: https://pastebin.com/qwGYmnFu

Anyway this error block the opening of the various buffers with the informations.

**Comment by dave2309** [comment]
After upgrading vdebug , I have the same error showing up during debug... when an ajax takes some times (difficult to measure that)

**Comment by BlackIkeEagle** [comment]
Could you create simple steps to reproduce? I have tried to reproduce but not yet encountered this socket.timeout issue

**Comment by BlackIkeEagle** [comment]
@Mte90 I don't think the timeout is related to the empty stacktrace

**Comment by Mte90** [comment]
when I tested I changed the code to get more seconds, as I can remember the error was still there.

**Comment by dave2309** [comment]
It is difficult to make steps to reproduce. But for me I can reproduce each time I have a process on backend that takes more than 30s to process. eg. series of ajax calls (short ones) are perfectly fine. Then one request needs to wait for a backend task to finish like an upload to some server, big file, upload times is more than 30s. then the error message appear on vim.
I have tested two versions of vim: (on ubuntu)
version: 2:8.1.2269-1ubuntu5
and version: 2:8.2.1767-0york0~20.04
same result

**Comment by dave2309** [comment]
Something I did which endup losing the connection.
Put a breakpoint at a first line method.
next is `sleep(30);`
then another breakpoint next line.

When running. Vim breaks at the first breakpoint. Then when pressing F5 then display a `connection closed` after around 10s.

**Comment by dave2309** [comment]
So `Error starting Vdebug: <class 'socket.timeout'>` appears when performing an `xhr` call.
Otherwise the message is `Connection to the debugger has been closed`.
But both occur if the "task" takes more than 4s. until 4s everything is fine. 5s then errors shows up.

**Comment by BlackIkeEagle** [comment]
@dave2309 thanks, I'll look into it further

**Comment by dave2309** [comment]
I may have found something

**Comment by BlackIkeEagle** [comment]
@dave2309 the client should not set the timeout there, I overlooked that

**Comment by BlackIkeEagle** [comment]
Thanks for the additional input, this helped finding the issue

**Comment by dave2309** [comment]
nm
I use vdebug quite intensively. I would have love to PR but I don't have enough knowledge of vdebug internal to propose yet.
Glad I could help
