### ISSUE TITLE
Bug! Please, help somebody!

### ISSUE THREAD

**Issue by terminator-ivanovich** [vim-vdebug/vdebug#485]
Arch Linux Kernel 5.4.64 (linux-lts package) system is stable
Vim  - 8.2.0814
Xdebug - 2.9.6
php - 7.4.7
installed python 3.8.5
Аfter closing first debugging session by F6 and closing all debugging windows also by F6, the NEXT debugging session start with so ugly message "vim.error: attempt to refer to deleted buffer". What is this? What is wrong with me, with my life and my vim-vdebug infrastructure?!

**Comment by Phosphenius** [comment]
I'm experiencing the same issue with an almost identical setup. I have to restart vim for every debugging session. 

PHP v7.4.10
Xdebug v2.9.6
Vim v8.2.1704

**Comment by terminator-ivanovich** [comment]
Now I debug in phpstorm, sorry vim. Phpstorm - no problem, but only on good hardware.

**Comment by BlackIkeEagle** [comment]
Sorry, My mistake, fix is coming

**Comment by BlackIkeEagle** [comment]
If you could verify, that would be awesome, thanks
