### ISSUE TITLE
Can't exit debugger ui

### ISSUE THREAD

**Issue by mlapai** [vim-vdebug/vdebug#486]
If i use f6 to close the DebuggerWatcher, DebuggerStatus and DebuggerStack, next debug session bugs out with an error:
```
Error starting Vdebug: <class 'pynvim.api.common.NvimError'>   
```
and i need to restart vim in order to use  vdebug again.

If i leave them open however, next session works as intented.
Besides that, when using path maps only every 3rd request is entering session - exactly third, so there is that.....
How da hell is it possible that every third, and specifically 3rd request is always working, i'm really confused.

Success on 3rd request is only happening when using path maps, if i use debugger on some random project without path maps, it works on every request.

apparently he listens on the port 9000, but only every 3rd request he finds the client

Does anyone has the idea what's going on here?

**Comment by BlackIkeEagle** [comment]
I think this is the same issue as #485, so the fix is coming soon

**Comment by BlackIkeEagle** [comment]
If you could verify, that would be awesome, thanks
