### ISSUE TITLE
Error starting Vdebug: <class 'pynvim.api.common.NvimError'>

### ISSUE THREAD

**Issue by fabiosal** [vim-vdebug/vdebug#487]
The debugger works just the first time, after that when i try to start the debugger  I receive this error:
`Error starting Vdebug: <class 'pynvim.api.common.NvimError'>`
a new tab is created with two windows but the one with the debugger console/stacktrace is empty.

I'm using 
NVIM v0.4.3
an updated version of vdebug: commit  88e08263d20be875af74c5ee9df43af9bb98ecea
pynvim Version: 0.4.2

thank you

**Comment by mlapai** [comment]
@fabiosal having the same issue, and some additional ones described in https://github.com/vim-vdebug/vdebug/issues/486

**Comment by BlackIkeEagle** [comment]
same as #486 and #485 so the fix is coming soon

**Comment by BlackIkeEagle** [comment]
If you could verify, that would be awesome, thanks

**Comment by fabiosal** [comment]
Back to normal, 
thank you
