### ISSUE TITLE
Bug. Double-click on superglobals variables 

### ISSUE THREAD

**Issue by terminator-ivanovich** [vim-vdebug/vdebug#489]
Arch5.4, vim8.2, python3.8.5, xdebug2.9.6, php7.4.10
Doubleclick or enter on superglobals vars return this mistake.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/neomatrix/.vim/bundle/vdebug/python3/vdebug/debugger_interface.py", line 93, in handle_double_click
    return self.event_dispatcher.by_position(self.session_handler)
  File "/home/neomatrix/.vim/bundle/vdebug/python3/vdebug/event.py", line 803, in by_position
    return event.run()
  File "/home/neomatrix/.vim/bundle/vdebug/python3/vdebug/event.py", line 155, in run
    context_res = self.api.property_get(name)
  File "/home/neomatrix/.vim/bundle/vdebug/python3/vdebug/dbgp.py", line 355, in property_get
    return self.send_cmd(
  File "/home/neomatrix/.vim/bundle/vdebug/python3/vdebug/dbgp.py", line 255, in send_cmd
    return res_cls(msg, cmd, args, self)
  File "/home/neomatrix/.vim/bundle/vdebug/python3/vdebug/dbgp.py", line 120, in __init__
    Response.__init__(self, response, cmd, cmd_args, api)
  File "/home/neomatrix/.vim/bundle/vdebug/python3/vdebug/dbgp.py", line 22, in __init__
    self.__parse_error()
  File "/home/neomatrix/.vim/bundle/vdebug/python3/vdebug/dbgp.py", line 42, in __parse_error
    raise DBGPError(msg_el.text, code)
vdebug.dbgp.DBGPError: ('can not get property', '300')

**Comment by BlackIkeEagle** [comment]
I've tested with gvim 8.2.1805 and have no issues, going to test with stock vim from arch next

**Comment by BlackIkeEagle** [comment]
Well that's completely sad, Arch default vim does not have proper or working python3 support?

**Comment by terminator-ivanovich** [comment]
I installed gvim. Arch default gvim support python3
``
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 17 2020 21:54:53)
Included patches: 1-1704
Compiled by Arch Linux
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       +tcl/dyn
-autoservername    +folding           +multi_byte        +termguicolors
+balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
+browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              +perl/dyn          +title
+clientserver      +job               +persistent_undo   +toolbar
+clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           +python/dyn        +visual
+conceal           +linebreak         +python3/dyn       +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       +lua/dyn           +ruby/dyn          +wildmenu
+dialog_con_gui    +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       +X11
+dnd               +mouse             +sound             -xfontset
-ebcdic            +mouseshape        +spell             +xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              +mouse_gpm         +statusline        +xsmp_interact
+ex_extra          -mouse_jsbterm     -sun_workshop      +xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gio-unix-2.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/at-spi-2.0 -pthread    -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -D_REENTRANT  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.32/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lz -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0  -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lelf    -lcanberra  -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.32/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/5.32/core_perl/CORE -lperl -lpthread -ldl -lm -lcrypt -lutil -lc   -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lm

**Comment by terminator-ivanovich** [comment]
I commented all vdebug configs, described on 490 issue - and vdebug start work nicely - double-click on superglobals works good and F6 also works good. My problem in vdebug configs. Thanks, @BlackIkeEagle

**Comment by BlackIkeEagle** [comment]
Ok since its the config I'm closing this one, thanks
