### ISSUE TITLE
vdebug always stops at the entry point of the code instead of directly stopping at the set breakpoint

### ISSUE THREAD

**Issue by asadsureify** [vim-vdebug/vdebug#492]
Using vdebug with nvim and xdebug
vdebug always stops at the entry point of the code instead of directly stopping at the set breakpoint

**Comment by BlackIkeEagle** [comment]
@asadsureify that is default behaviour, if you don't want that disable `break_on_open`

see https://github.com/vim-vdebug/vdebug/blob/master/doc/Vdebug.txt#L864

to change this you can add:

```
" vdebug settings
let g:vdebug_options = {
    \'break_on_open': 0
\}
```
in your init.vim

**Comment by asadsureify** [comment]
thanks
