### ISSUE TITLE
Error starting Vdebug: <class 'pynvim.api.common.NvimError'>

### ISSUE THREAD

**Issue by stephenplatz** [vim-vdebug/vdebug#494]
I've already looked at #487, #485 and #486. I just pulled f61a9672fcf38e8f99a5c2ffcdf36d52b2beb802, but it's frankly been a while since I've updated. I can't start a debugging session at all, even after starting vim again.

NVIM v0.3.8

**Comment by lucc** [comment]
Can you post the full stack trace?

**Comment by stephenplatz** [comment]
Here's what I have from a first try:
`- [Debug] {Wed 02 2020 13:11:35} keymapper: reload_keys
- [Debug] {Wed 02 2020 13:11:35} Closing the socket
- [Debug] {Wed 02 2020 13:11:35} Closing the socket
- [Debug] {Wed 02 2020 13:11:35} Started
- [Debug] {Wed 02 2020 13:11:35} Listening on port 9000
- [Debug] {Wed 02 2020 13:11:39} Stopping server
- [Debug] {Wed 02 2020 13:11:39} Finishing socket server
- [Info] {Wed 02 2020 13:11:39} Vdebug stopped waiting for a connection
- [Debug] {Wed 02 2020 13:11:39} keymapper: reload_keys
- [Debug] {Wed 02 2020 13:11:39} Creating hidden buffer: []
- [Debug] {Wed 02 2020 13:11:39} Creating hidden buffer: []
- [Debug] {Wed 02 2020 13:11:39} Creating hidden buffer: []
- [Debug] {Wed 02 2020 13:11:39} Creating hidden buffer: []
- [Debug] {Wed 02 2020 13:11:39} Creating hidden buffer: [' 11000   | True   | line        | /home/steve/Applications/passtab-visitor-management/sites/all/modules/contrib/agreement/agreement.module:162', ' 11001   | True   | line        | /home/steve/Applications/passtab-visitor-management/sites/all/modules/contrib/agreement/agreement.module:1217', ' 11002   | True   | line        | /home/steve/Applications/passtab-visitor-management/sites/all/modules/custom/passtab_custom/passtab_custom.module:14']
- [Debug] {Wed 02 2020 13:11:39} Creating hidden buffer: []`

**Comment by stephenplatz** [comment]
I guess I'm not sure how to provide something useful, I don't think you're looking for the vdebug logs.

**Comment by lucc** [comment]
I was hoping for a python stack trace that belongs to your headline for this issue. ` <class 'pynvim.api.common.NvimError'>` looks like the type of an exception that I assumed was thrown.

Maybe you can also give exact steps what to do to reproduce this (php ini setting for xdebug, nvim command line, steps you perform).

**Comment by stephenplatz** [comment]
I'd be happy to add a python stack trace here, but the error above is just appearing in my editor.

My php.ini simply has these settings:

xdebug.max_nesting_level = 256    
xdebug.show_exception_trace = 0    
xdebug.collect_params = 0    
xdebug.remote_enable = 1    
xdebug.remote_autostart = 0                                        
xdebug.remote_host = ${LANDO_HOST_IP}    
xdebug.remote_log = /tmp/xdebug.log

I'm using vdebug in the regular way I've always done, in this case I set a couple of breakpoints, hit <F5> and wait for the debugger. It appears that when a connection is made, the above error is thrown. What's the best way to get a stack trace?

**Comment by lucc** [comment]
You can check `:help VdebugLogWindow` and `help VdebugOptions-debug_file`.

I will try to reproduce tomorrow (at my work computer).

**Comment by stephenplatz** [comment]
The log window opens when the error occurs without any additional information, it's completely empty. I was going to provide the log output above, but thought that it wouldn't be helpful. I'll provide a log here, there doesn't seem to be much in it, log level 2:

- [Debug] {Wed 02 2020 14:05:29} keymapper: reload_keys
- [Debug] {Wed 02 2020 14:05:29} Closing the socket
- [Debug] {Wed 02 2020 14:05:29} Closing the socket
- [Debug] {Wed 02 2020 14:05:29} Started
- [Debug] {Wed 02 2020 14:05:29} Listening on port 9000
- [Debug] {Wed 02 2020 14:05:32} Stopping server
- [Debug] {Wed 02 2020 14:05:32} Finishing socket server
- [Info] {Wed 02 2020 14:05:32} Vdebug stopped waiting for a connection
- [Debug] {Wed 02 2020 14:05:32} keymapper: reload_keys
- [Debug] {Wed 02 2020 14:05:33} Creating hidden buffer: [' 11000   | True   | line        | /home/steve/Applications/passtab-visitor-management/sites/all/modules/contrib/agreement/agreement.module:1217']
- [Debug] {Wed 02 2020 14:05:33} Creating hidden buffer: []
- [Debug] {Wed 02 2020 14:05:33} Creating hidden buffer: []
- [Debug] {Wed 02 2020 14:05:33} Creating hidden buffer: []
- [Debug] {Wed 02 2020 14:05:33} Creating hidden buffer: []
- [Debug] {Wed 02 2020 14:05:33} Creating hidden buffer: []

Here's a screenshot for what it's worth:

![Screenshot_2020-12-02_14-05-08](https://user-images.githubusercontent.com/519156/100937239-8fb33000-34a7-11eb-92d8-cf690b085561.png)

**Comment by Mte90** [comment]
I think that is the same of https://github.com/vim-vdebug/vdebug/issues/403

**Comment by Mte90** [comment]
I did a bounty for that issue https://www.bountysource.com/issues/76208208-open-the-debug-without-any-stacktrace

**Comment by stephenplatz** [comment]
Upgrading my Neovim to v0.4.4 solved this and other issues for me.
