### ISSUE TITLE
Stack trace on connect

### ISSUE THREAD

**Issue by kkuchta** [vim-vdebug/vdebug#60]
I'm getting the following error when connecting:

![Error](http://i.imgur.com/2gIdON5.png)

The text is:

```
Waiting for a connection (Ctrl-C to cancel, this message will self-destruct in  20  seconds...)
An error occured: <type 'exceptions.ValueError'>
Traceback (most recent call last):
  File "/Users/kevin/main_dotfiles/dotvim/bundle/vdebug/plugin/python/start_vdebug.py", line 31, in run
    self.runner.run()
  File "/Users/kevin/main_dotfiles/dotvim/bundle/vdebug/plugin/python/vdebug/runner.py", line 160, in run
    self.open()
  File "/Users/kevin/main_dotfiles/dotvim/bundle/vdebug/plugin/python/vdebug/runner.py", line 74, in open
    raise e
ValueError: invalid literal for int() with base 10: ''  
```

The setup I have is: an Ubuntu VM running PHP + xdebug (running in virtualbox).  The host machine is OS X (10.8) with the latest version of MacVim.  When I hit `<F5>` in macvim, the UI hangs for a bit until either it times out or I run `curl https://www.vmUrl.com?XDEBUG_SESSION=true`, at which point the above stack trace bops up in macvim (and curl returns `curl: (35) Unknown SSL protocol error in connection to www.expensify.com:443`).

Is this an issue with xdebug and ssl, or is that ssl error just a byproduct of something going wrong with the connection to vdebug (as evidenced by the stack trace)?  Or any other ideas?

**Comment by cdaringe** [comment]
I get the parse error pretty regularly.

```
An error occured: <class 'xml.etree.ElementTree.ParseError'>
Traceback (most recent call last):
  File "/home/cdieringer/.vim/bundle/vdebug/plugin/python/start_vdebug.py", line 119, in handle_eval
    return self.runner.eval(args)
  File "/home/cdieringer/.vim/bundle/vdebug/plugin/python/vdebug/runner.py", line 288, in eval
    self.ui.watchwin.accept_renderer(rend)
  File "/home/cdieringer/.vim/bundle/vdebug/plugin/python/vdebug/ui/vimui.py", line 377, in accept_renderer
    self.write(renderer.render())
  File "/home/cdieringer/.vim/bundle/vdebug/plugin/python/vdebug/ui/vimui.py", line 560, in render
    properties = self.response.get_context()
  File "/home/cdieringer/.vim/bundle/vdebug/plugin/python/vdebug/dbgp.py", line 146, in get_context
    for c in list(self.as_xml()):
  File "/home/cdieringer/.vim/bundle/vdebug/plugin/python/vdebug/dbgp.py", line 71, in as_xml
    self.xml = ET.fromstring(self.response)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: reference to invalid character number: line 2, column 239
```

For example, if i do `:VdebugEval $v[0]`, it renders properly with my object breakdown, just as expected:

<img width="1541" alt="good" src="https://cloud.githubusercontent.com/assets/1003261/12099368/3b08dd8c-b2e5-11e5-9058-3a2f372ad975.png">

however, if i do a  `:VdebugEval (array) $v[0]` (key take away there is that I tried to cast a StdClass to array):

<img width="1541" alt="bad" src="https://cloud.githubusercontent.com/assets/1003261/12099389/5ec954ae-b2e5-11e5-8f87-a35a29ed67f4.png">

**Comment by joonty** [comment]
Hi @cdaringe, could you provide a debug log according to the instructions [here](https://github.com/joonty/vdebug#debugging)? That would show me the raw XML, so I can work out what's causing the error for you.

Thanks!

**Comment by cdaringe** [comment]
thanks @joonty!  i will do so.  ATM i'm yakking my brains out with food poisoning, so post-TMI and passing of the the aforementioned circumstances, i'll get right on it ;)  thanks so much.  vdebug has been so critical to workflow i dont know what id do without it

**Comment by joonty** [comment]
Yikes! Hope you feel better soon!

On Tue, 12 Jan 2016, 22:04 Christopher Dieringer <notifications@github.com>
wrote:

> thanks @joonty <https://github.com/joonty>! i will do so. ATM i'm yakking
> my brains out with food poisoning, so post-TMI and passing of the the
> aforementioned circumstances, i'll get right on it ;) thanks so much.
> vdebug has been so critical to workflow i dont know what id do without it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joonty/vdebug/issues/60#issuecomment-171074828>.
>
-- 
https://twitter.com/joonty

**Comment by cdaringe** [comment]
[here](https://gist.github.com/cdaringe/c60b074eac92537b9b3e) it is.  I hope it has something helpful in there.  note, i set a breakpoint next to the line where some offending code used to be, did a `VdebugEval (array) $value` to produce the error (as that's what the old code did), removed the breakpoint and continued.

**Comment by joonty** [comment]
@cdaringe can you just try `VdebugEval $value`? I wonder whether the type prefix is causing weirdness.

It's falling over on the `name` attribute of this part of the return XML from Xdebug:

```xml
<property name="&#0;*&#0;dbObj" address="...
```

Not seen anything like that before, but that name doesn't decode properly (try it in [this xml decoder](http://coderstoolbox.net/string/#!encoding=xml&action=decode&charset=utf_8)), which is why it's collapsing.

**Comment by cdaringe** [comment]
hey @joonty, if you take a peek above, I demonstrated that just `VdebugEval $v[0]` indeed works just fine.  is this what you mean?

**Comment by joonty** [comment]
@cdaringe sorry, you're right - it's been a while since I looked at this issue and I didn't read back up on it! It looks like this *might* be an issue in Xdebug, as I can see that it's receiving the correctly encoded eval string, but it's returning something garbled. If you make sure your Xdebug is up to date, it may be worth getting @derickr involved and seeing what his thoughts are.

**Comment by derickr** [comment]
I will look at this, but instead of "eval", you really should be using "property_get".

**Comment by derickr** [comment]
Okay. I check this, and it's not a "bug". What happens is the same as doing this:

```
<?php
class Foo {
    private $bar =42;
}

$a = new foo;
var_dump( (array) $a );
?>

Private properties in PHP are encoded with "\0*\" in front of their name, and that shows up when you cast to an array. Standard PHP doesn't *show* that \0, but it's there - check with ```php -n test.php | od -t x1```.

Xdebug needs to convert \0foo\0bar into XML, and as XML doesn't allow for \0 characters, it turns it into &#0;. However, that's sadly not supported in the XML standard either... so I'm not sure what to do about that.

However, using "property_get -n $v" instead of "eval -- (array) $v" will fix this. Morale: don't use "eval" for variable value fetching.

**Comment by joonty** [comment]
Thanks a lot for the insight @derickr, that's really helpful. I think this has come up before, where you've suggested using property_get. The thing is that in this context, vdebug allows the user to evaluate any valid php expression, not just a single property. I'd toyed with the idea of trying to determine whether it was a property and either eval or property_get as appropriate, but decided it was too much work for too little gain.

Makes sense about the null byte. Since the python library clearly doesn't support it I'm probably best doing a string sanitize on the raw xml before parsing.

Thanks again

**Comment by cdaringe** [comment]
mystery revealed.

> probably best doing a string sanitize on the raw xml before parsing

:game_die: :game_die: :game_die: :game_die: :game_die: yahtzee!

**Comment by gquemener** [comment]
Hello :wave: 

I would like to know if there's an update regarding the pre-parsing sanitization @joonty ?

I've run into a similar issue today, the parsed xml is:

```xml
<response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="context_get" transaction_id="17" context="0">
    <property name="$deferred" fullname="$deferred" type="object" classname="Amp\Deferred" children="1" numchildren="2" page="0" pagesize="32">
        <property name="resolver" fullname="$deferred-&gt;resolver" facet="private" type="object" classname="class@anonymous&#0;/app/vendor/amphp/amp/lib/Deferred.php0x7fa0c40e72d3" children="1" numchildren="4">
        </property>
        <property name="promise" fullname="$deferred-&gt;promise" facet="private" type="object" classname="Amp\Internal\PrivatePromise" children="1" numchildren="1">
        </property>
    </property>
</response>
```

which is invalid (because of "invalid character number" `&#0;`).

The full vdebug error trace is:

```
- [ERROR] {Tue 17 2018 13:05:36} An error occured: <class 'xml.etree.ElementTree.ParseError'>
Traceback (most recent call last):
  File "/home/gildas/.vim/plugged/vdebug/pythonx/vdebug/event.py", line 524, in dispatch_event
    Dispatcher.events[name](self.__session_handler).run(*args)
  File "/home/gildas/.vim/plugged/vdebug/pythonx/vdebug/event.py", line 439, in run
    self.ui.windows.watch().accept_renderer(rend)
  File "/home/gildas/.vim/plugged/vdebug/pythonx/vdebug/ui/vimui.py", line 513, in accept_renderer
    self.write(renderer.render())
  File "/home/gildas/.vim/plugged/vdebug/pythonx/vdebug/ui/vimui.py", line 736, in render
    properties = self.response.get_context()
  File "/home/gildas/.vim/plugged/vdebug/pythonx/vdebug/dbgp.py", line 132, in get_context
    for c in list(self.as_xml()):
  File "<string>", line None
xml.etree.ElementTree.ParseError: reference to invalid character number: line 2, column 397
``` 

And here's the PHP version I'm using:
```
PHP 7.2.3 (cli) (built: Mar  5 2018 21:28:31) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans
```

Sorry if this has been issued before, I haven't found any reference to it.

Thanks in advance.

**Comment by BlackIkeEagle** [comment]
@gquemener could you create a new ticket please
