### ISSUE TITLE
cannot connect to xdebug - `Connection to the debugger has been closed`

### ISSUE THREAD

**Issue by mrotaru** [vim-vdebug/vdebug#78]
I'm trying to connect to xdebug on a remote VM, but it just fails instantly with "Connection to the debugger has been closed". I created [github repo](https://github.com/mihai-rotaru/xdebug-test) with a Vagrant VM which reproduces this issue. Once up and running, the VM is reachable at 33.33.33.10  and has xdebug loaded (it appears in phpinfo output ). I have also checked that `xdebug.ini` is parsed.

Logging doesn't help much:

```
- [Info] {Fri 19 2013 11:59:14} Connection to the debugger has been closed
```

Looking through the source code, it seems this message is shown when a socket is closed, but I don't know where to go from here.

vdebug settings:

```
g:vdebug_options      
{'debug_file': 'vdebug_log',
'debug_file_level': 2,
'watch_window_style': 'expanded',
'marker_default': '*',
'continuous_mode': 0,
'ide_key': '',
'break_on_open': 1,
'on_close': 'detach',
'path_maps': {'/var/www': 'C:\code\xdebug-test'},
'marker_closed_tree': '+',
'timeout': 20,
'port': 9000,
'marker_open_tree': '-',
'debug_window_level': 1,
'server': '33.33.33.10'}
```

Also, here's some output from Apache's `access.log`:

```
33.33.33.1 - - [19/Apr/2013:12:26:11 +0100] "GET /debug_me.php HTTP/1.1" 200 314 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:20.0) Gecko/20100101 Firefox/20.0"
```

**Comment by jmarceli** [comment]
For Varying Vagrants Vagrant (https://github.com/Varying-Vagrant-Vagrants/VVV) use following `path_maps`:
    
    let g:vdebug_options["path_maps"] = {'/srv/www' : '/Users/janek/Documents/Work/vagrant/www' }

What is more it is important to execute `xdebug_on` in guest box.

**Comment by subhojit777** [comment]
I am trying to use this plugin for debugging Drupal application. When I press `<F5>` I get this message "Connection to the debugger has been closed". Following are the environment configuration that I am using:

OS - Ubuntu 14.04
Web server - Apache mpm worker with PHP FPM
Xdebug configuration in `/etc/php5/fpm/php.ini` -
```
zend_extension=/usr/lib/php5/20121212/xdebug.so
xdebug.remote_autostart=1
xdebug.remote_enable=1
xdebug.remote_handler=dbgp
xdebug.remote_host=localhost
xdebug.remote_port=9000
```
Vdebug configurations - Default

I get this message when I press `<F5>` "Connection to the debugger has been closed".

I have tried changing port numbers to 9001, 9002 and 8000, but still not working.

Can anyone please tell me what I am missing, because I was able to debug Drupal application using this plugin earlier in some other machine.

**Comment by chrissound** [comment]
I find it usually helpful to enable the log by setting
xdebug.remote_log = /tmp/somefile

**Comment by joonty** [comment]
Hi @subhojit777, are you using vagrant or just debugging locally as normal?

@chrissound thanks for that, good suggestion - give that a go @subhojit777. You can also enable vdebug's logs by following [these instructions](https://github.com/joonty/vdebug#debugging), which might shed some light.

**Comment by subhojit777** [comment]
I have added these settings in `.vimrc`
```
let g:vdebug_options= {
\    "port" : 9001,
\    "server" : 'localhost',
\    "ide_key" : 'XDEBUG_ECLIPSE',
\    "debug_file_level" : 2,
\    "debug_file" : '~/vdebug.log',
\}
```
along with the setting that @chrissound has suggested.
In `~/vdebug.log` I am getting this:
`[Info] {Tue 01 2015 18:32:16} Connection to the debugger has been closed`'

In `/tmp/xdebug.log` I am getting this:
```
Log opened at 2015-12-01 12:39:02
I: Connecting to configured address/port: localhost:9001.
E: Could not connect to client. :-(
Log closed at 2015-12-01 12:39:02
```

Still I am getting that connection refuse message. FYI I am able to setup the debugger in PHPStorm.

**Comment by subhojit777** [comment]
@joonty The vdebug settings mentioned above are same as I am using for PHPStorm

**Comment by subhojit777** [comment]
Another thing - while debugging do we need to append idekey to the page url that we are debugging, something like this: `http://site.local/page?idekey=XDEBUG`

**Comment by joonty** [comment]
Have you tried it without the IDE key? Just set `g:vdebug_options["ide_key"] = ""`, and it will pick up any connection. I imagine that what's happening is the IDE key is not being passed through when you debug. According to the Xdebug docs, the correct query parameter is `XDEBUG_SESSION_START=session_name`, so in your case it would be `http://site.local/page?XDEBUG_SESSION_START=XDEBUG_ECLIPSE`. But as I say, try it without the IDE key first, get that working, then move on to adding the IDE key.

**Comment by subhojit777** [comment]
AWESOME!! Thank you so much!! Thanks for this wonderful plugin :)

**Comment by subhojit777** [comment]
I cleared out `ide_key` and it started working.

**Comment by joonty** [comment]
Great to hear it! If you need an IDE key for whatever reason (but that's really only if you have multiple sessions going on at the same time) you can try using the XDEBUG_SESSION_START parameter as I mentioned above.

Thanks

**Comment by subhojit777** [comment]
Thanks!

**Comment by subhojit777** [comment]
Anyone facing the same problem - **try changing the port number**. In my case the default xdebug port 9000 was busy (I figured that out from PhpStorm message), so I had to change it. And after you change it make sure you have conveyed that information to vdebug plugin by adding this in `.vimrc`:
```
let g:vdebug_options= {
\    "port" : 9001,
\    "server" : 'localhost',
\    "debug_file_level" : 2,
\    "debug_file" : '~/vdebug.log',
\}
```

**Comment by Iazel** [comment]
Hello guys! I'm trying to use docker and this error popup. 
My current vdebug_options:
```vim
let g:vdebug_options = {
      \ 'port': '9001',
      \ "server": '',
      \ 'ide_key': '', 
      \ 'path_maps': {'/var/www/html': expand('<sfile>:h:p')}, 
      \ 'debug_file': '/tmp/vdebug.log', 
      \ 'debug_file_level': 2 
      \ }
```
However in the log there's no useful information, only this:
```
- [Info] {lun 01 2016 12:22:53} Connection to the debugger has been closed
```

My Dockerfile configuration:
```Dockerfile
FROM php:7-fpm
RUN yes | pecl install xdebug
ADD ./xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini
```

The xdebug.ini:
```ini
xdebug.remote_enable=1;
xdebug.remote_port=9001;
xdebug.remote_connect_back=1;
xdebug.max_nesting_level=200
xdebug.idekey=""
zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20151012/xdebug.so
```

This is the relevant bit of the docker-compose.yml
```yml
php:
    build: ./docker/php/
    expose:
        - 9000
    ports:
        - '9001:9001'
    links:
        - mysql
    volumes_from:
        - app
```

Any ideas?

**Comment by nathanielks** [comment]
@Iazel you're a lifesaver. My understanding of `remote_port` was the same as yours before. That totally makes sense now!
